
propertySearchBingMap={map:"",propertiesDataArray:new Array,locations:[],locs:new Array,pushpins:new Array,pushpinClass:new Array,FLYOUT_CLASS:"m-map-zoom-flyout t-font-bold",startTimeout:"",rewardsFlag:$(".my-stays-map"),MM:Microsoft.Maps,overMap:false,pushPinLatestLatitude:$("#pushpin-latestStayLatitude"),pushPinLatestLongitude:$("#pushpin-latestStayLongitude"),el:null,init:function(){if(window.parent!=null)
{window.parent.scrollTo(0,0);}
if($('div#map').length!=0){var mapStateCookie=getCookie("mapState"),data=$(':hidden[name=moduleState]').val(),currentView=$('#view-controls').data('currentview');if(mapStateCookie!=null&&mapStateCookie!="")
{data=mapStateCookie;}
if(typeof currentView==="undefined"&&(data!="hide"||$('#close-compare-map').length!=0)||(typeof currentView!="undefined"&&(currentView=="mapView"))){propertySearchBingMap.generatePushpinData();propertySearchBingMap.getMap(propertySearchBingMap);}
else{var mapToggleOff=$('#map-toggle-off');if(mapToggleOff.length!=0){mapToggleOff.attr('checked',true);}}}
if(document.getElementById("map-container")){if(document.getElementById("map-toggle-on")){document.getElementById("map-toggle-on").onclick=propertySearchBingMap.toggleMap;}
if(document.getElementById("map-toggle-off")){document.getElementById("map-toggle-off").onclick=propertySearchBingMap.toggleMap;}}},getCookie:function(c_name)
{var i,x,y,ARRcookies=document.cookie.split(";");for(i=0;i<ARRcookies.length;i++)
{x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);x=x.replace(/^\s+|\s+$/g,"");if(x==c_name)
{return unescape(y);}}},addLoadEvent:function(func){var oldonload=window.onload;if(typeof window.onload!='function'){window.onload=func;}else{window.onload=function(){oldonload();func();}}},pushpinObj:function(){this.number;this.lat;this.longitude;this.type;this.overlapList;},generatePushpinData:function(){var pushPinLatObj=document.getElementsByName("pushpin-lat");var pushPinLongObj=document.getElementsByName("pushpin-long");var pushPinTypeObj=document.getElementsByName("pushpin-type");var pushPinBrandObj=document.getElementsByName("pushpin-brand");var pushPinMarshaCodeObj=document.getElementsByName("pushpin-marshaCode");var pushPinNumberObj=document.getElementsByName("pushpin-number");for(i=0;i<pushPinLatObj.length;i++){var propertyData=new propertySearchBingMap.pushpinObj,propertyDataLat=pushPinLatObj[i],propertyDataLong=pushPinLongObj[i],propertyDataType=pushPinTypeObj[i],propertyDataBrand=pushPinBrandObj[i],propertyDataMarsha=pushPinMarshaCodeObj[i],propertyDataNum=pushPinNumberObj[i];if(typeof propertyDataLat!=="undefined"){propertyData.lat=propertyDataLat.value;}
else{propertyData.lat=0;}
if(typeof propertyDataLong!=="undefined"){propertyData.longitude=propertyDataLong.value;}
else{propertyData.longitude=0;}
if(typeof propertyDataType!=="undefined"){propertyData.type=propertyDataType.value;}
else{propertyData.type="";}
if(typeof propertyDataBrand!=="undefined"){propertyData.brand=propertyDataBrand.value;}
else{propertyData.brand="";}
if(typeof propertyDataMarsha!=="undefined"){propertyData.marshaCode=propertyDataMarsha.value;}
else{propertyData.marshaCode="";}
if(typeof propertyDataNum!=="undefined"){propertyData.pushpinNumber=propertyDataNum.value-1;}
else{propertyData.pushpinNumber=0;}
propertySearchBingMap.propertiesDataArray.push(propertyData);}},mouseEvent:function(e){if(e.eventName=='mouseout'){propertySearchBingMap.overMap=false;}else if(e.eventName=='mouseover'){propertySearchBingMap.overMap=true;}},getMap:function(mapObj){try{propertySearchBingMap.MM.loadModule('Microsoft.Maps.Overlays.Style',{callback:function(){var mapOptions={credentials:document.getElementById("bingKey").value,mapTypeId:propertySearchBingMap.MM.MapTypeId.road,enableClickableLogo:false,customizeOverlays:true,enableSearchLogo:false,tileBuffer:Number(document.getElementById("tileBuffer").value)};propertySearchBingMap.map=new propertySearchBingMap.MM.Map(document.getElementById("map"),mapOptions);var propertyData,loc;for(var x=0;x<propertySearchBingMap.propertiesDataArray.length;x++){propertyData=propertySearchBingMap.propertiesDataArray[x];loc=new Array(Number(propertyData.lat),Number(propertyData.longitude));propertySearchBingMap.locs.push(loc);propertySearchBingMap.locations.push(new propertySearchBingMap.MM.Location(propertyData.lat,propertyData.longitude));if($(".my-stays-map").length>0){pushPinLatestLatitude=propertySearchBingMap.pushPinLatestLatitude.val();pushPinLatestLongitude=propertySearchBingMap.pushPinLatestLongitude.val();latestStayInfoId="flyout["+pushPinLatestLatitude+"]["+pushPinLatestLongitude+"]";latestStayInfoId=document.getElementById(latestStayInfoId);if(propertyData.lat==pushPinLatestLatitude&&propertyData.longitude==pushPinLatestLongitude){$(latestStayInfoId).removeClass("l-display-none");}}}
$("html").click(function(){if(!propertySearchBingMap.overMap){propertySearchBingMap.map.blur();}});$(".map-flyout").on("hover",function(){clearTimeout(propertySearchBingMap.startTimeout);});$(".map-flyout").on("mouseleave",function(){propertySearchBingMap.hideInfobox();});propertySearchBingMap.map.blur();propertySearchBingMap.MM.Events.addHandler(propertySearchBingMap.map,'mouseout',propertySearchBingMap.mouseEvent);propertySearchBingMap.MM.Events.addHandler(propertySearchBingMap.map,'mouseover',propertySearchBingMap.mouseEvent);mapObj.setMapView();}});}catch(e){mapObj.displayMapError();}},getFlyoutId:function(lat,long){try{var flyoutId="flyout["+lat+"]["+long+"]";return flyoutId;}catch(e){}},triggerPushpinClick:function(e){pushpinClass=e.target.getTypeName().split(" ");if(pushpinClass[1]=="RZ"){propertySearchBingMap.displayInfobox(e);}else{propertySearchBingMap.displayQuickView(e);}},displayQuickView:function(e){if(e.targetType=='pushpin'&&$('body.reservations').length==0){propertySearchBingMap.hideInfobox();pushpinClass=e.target.getTypeName().split(" ");if(pushpinClass[0]!="js-map-clustered"&&pushpinClass[1]!="RZ"){var pushpinMarshaCode=pushpinClass[2];var pushpinNumber=pushpinClass[3];if(propertySearchBingMap.rewardsFlag.length==0){hotelPanel.loadpanel(pushpinMarshaCode,pushpinNumber,true);}}
return false;}},displayInfobox:function(e){if(e.targetType=='pushpin'){e=e.target;}
var pix=propertySearchBingMap.map.tryLocationToPixel(e.getLocation(),propertySearchBingMap.MM.PixelReference.page);var flyoutId=propertySearchBingMap.getFlyoutId(e.getLocation().latitude,e.getLocation().longitude);var pushPinClass=e.getTypeName().split(" ");if(pushPinClass[0]=="js-map-clustered"){var infobox=document.getElementById("cp"+flyoutId);if($(".my-stays-map").length>0){marshaId=pushPinClass[4];}}else{if($(".my-stays-map").length>0){var infobox1=document.getElementById(flyoutId);var marshaId=pushPinClass[2];}else{var infobox=document.getElementById(flyoutId);}}
if($(".my-stays-map").length>0){for(index=0;index<propertySearchBingMap.propertiesDataArray.length;index++){propertyData=propertySearchBingMap.propertiesDataArray[index];if(!$("."+marshaId).hasClass("js-map-clustered")){$(".in-active-pin").removeClass(propertyData.marshaCode);}}
$(".propertyDetails").css({"display":"inline","z-index":"10000"});$(infobox1).removeClass("l-display-none").addClass("active "+marshaId);$("."+marshaId).not(".js-map-clustered").removeClass("in-active-stay").addClass("activeMarsha");}
propertySearchBingMap.hideInfobox();$(infobox).css("top",(pix.y-40)+"px");$(infobox).css("left",(pix.x+5)+"px");$(infobox).css("display","inline");$(infobox).css("z-index","10000");$(infobox).css("position","absolute");$(infobox).addClass("info-box");$('body').append(infobox);propertySearchBingMap.pushpinMouseoverHandler();propertySearchBingMap.startTimeout=setTimeout(function(){propertySearchBingMap.hideInfobox()},5000);return false;},hideInfobox:function(e){$('.info-box').css("display","none");if($(".my-stays-map").length>0){if($(".in-active-pin").hasClass("active")){$(".in-active-pin").not(".active").addClass("l-display-none");}
if($(".m-pushpin").hasClass("activeMarsha")){$(".m-pushpin").not(".activeMarsha").addClass("in-active-stay");}
$(".m-pushpin").removeClass("activeMarsha");$(".in-active-pin").removeClass("active");}
clearTimeout(propertySearchBingMap.startTimeout);},getCustomIcon:function(category){var iconStyle="/Images/Reservations/CSS_Backgrounds/map-sprite.png";iconStyle=iconStyle;return iconStyle;},displayMapError:function(){var errorBlockObj=document.getElementById("error-messages");var searchMapObj=document.getElementById("map-container");var mapCopyrightObj=document.getElementById("map-copyright");errorBlockObj!=undefined?errorBlockObj.className="l-display-block":"";searchMapObj!=undefined?searchMapObj.className="is-hidden":"";mapCopyrightObj!=undefined?mapCopyrightObj.className="is-hidden":"";},veDoHotelClustering:function(){try{var magicHPixelDiff=15;var magicVPixelDiff=15;if($(".my-stays-map").length>0){magicHPixelDiff=30;magicVPixelDiff=30;}
var pixel1=new propertySearchBingMap.MM.Point(0,0);var pixel2=new propertySearchBingMap.MM.Point(magicHPixelDiff,magicVPixelDiff);var llPoint1=propertySearchBingMap.map.tryPixelToLocation(pixel1,propertySearchBingMap.MM.PixelReference.control);var llPoint2=propertySearchBingMap.map.tryPixelToLocation(pixel2,propertySearchBingMap.MM.PixelReference.control);var magicLongDiff=Math.abs(llPoint1.longitude-llPoint2.longitude);var magicLatDiff=Math.abs(llPoint1.latitude-llPoint2.latitude);for(var outL=0;outL<propertySearchBingMap.propertiesDataArray.length;outL++){propertySearchBingMap.propertiesDataArray[outL].overlapList="";}
var tLatDist,tLongDist;for(var outL=0;outL<propertySearchBingMap.propertiesDataArray.length;outL++){for(var inL=outL+1;inL<propertySearchBingMap.propertiesDataArray.length;inL++){tLongDist=Math.abs(propertySearchBingMap.propertiesDataArray[inL].longitude-propertySearchBingMap.propertiesDataArray[outL].longitude);tLatDist=Math.abs(propertySearchBingMap.propertiesDataArray[inL].lat-propertySearchBingMap.propertiesDataArray[outL].lat);if((tLatDist<magicLatDiff)&&(tLongDist<magicLongDiff)){propertySearchBingMap.propertiesDataArray[inL].overlapList+=outL+",";propertySearchBingMap.propertiesDataArray[outL].overlapList+=inL+",";}}
propertySearchBingMap.propertiesDataArray[outL].overlapList=propertySearchBingMap.propertiesDataArray[outL].overlapList.substr(0,propertySearchBingMap.propertiesDataArray[outL].overlapList.length-1);}
var olArr1,olArr2;var foundOverlaps=false;do{foundOverlaps=false;for(var outL=0;outL<propertySearchBingMap.propertiesDataArray.length;outL++){if(propertySearchBingMap.propertiesDataArray[outL]!=null&&propertySearchBingMap.propertiesDataArray[outL].overlapList!=""){olArr1=propertySearchBingMap.propertiesDataArray[outL].overlapList.split(",");for(x in olArr1){if(propertySearchBingMap.propertiesDataArray[olArr1[x]]!=null&&propertySearchBingMap.propertiesDataArray[olArr1[x]].overlapList!=""){olArr2=propertySearchBingMap.propertiesDataArray[olArr1[x]].overlapList.split(",");for(y in olArr2){if(typeof olArr2[y]=='string'&&(parseInt(olArr2[y],10)!=outL)&&(propertySearchBingMap.propertiesDataArray[outL].overlapList.match("(?:,|^)"+olArr2[y]+"(?:,|$)")==null)){foundOverlaps=true;propertySearchBingMap.propertiesDataArray[outL].overlapList+=","+olArr2[y];}}}}}}}while(foundOverlaps);propertySearchBingMap.veSetClusteredPins();}catch(e){}},veSetClusteredPins:function(){var olArr,propertyData,loc,pushpin,title,desc,icon,script,flyoutStr,pushpinClass;propertySearchBingMap.map.entities.clear();$(".map-zoom-flyout").remove();if($(".my-stays-map").length>0){var pushPinOffsetY=$("#pushpin-textOffsetY");var pushPinOffsetX=$("#pushpin-textOffsetX");var pushPinShowText=$("#pushpin-showText");var pushPinShowTextCluster=$("#pushpin-showTextCluster");var pushPinShowCluster=$("#pushpin-showCluster");if(pushPinOffsetY&&pushPinOffsetX&&pushPinShowText&&pushPinShowTextCluster&&pushPinShowCluster){pushPinOffsetX=pushPinOffsetX.val();pushPinOffsetY=pushPinOffsetY.val();pushPinShowText=pushPinShowText.val();pushPinShowTextClusterValue=pushPinShowTextCluster.val();pushPinShowClusterValue=pushPinShowCluster.val();}else{pushPinOffsetY=5;pushPinOffsetX=0;pushPinShowText=true;pushPinShowClusterValue=false;pushPinShowTextClusterValue=false;}
if(pushPinOffsetY==undefined){pushPinOffsetY=5;}else{pushPinOffsetY=Number(pushPinOffsetY);}
if(pushPinOffsetX==undefined){pushPinOffsetX=0;}else{pushPinOffsetX=Number(pushPinOffsetX);}}
var clustered=new Array();var isClustered=false;for(index=0;index<propertySearchBingMap.propertiesDataArray.length;index++){olArr=propertySearchBingMap.propertiesDataArray[index].overlapList.split(",");propertyData=propertySearchBingMap.propertiesDataArray[index];if($(".my-stays-map").length>0){var indexNumber=propertyData.pushpinNumber.toString();isClustered=false;if(pushPinShowClusterValue=='true'||pushPinShowClusterValue==true){for(var index2=0;index2<propertySearchBingMap.propertiesDataArray.length;index2++){if(index2!=index){var propertyData2=propertySearchBingMap.propertiesDataArray[index2];var olArr2=propertyData2.overlapList.split(",");var index2Number=propertyData2.pushpinNumber.toString();if(($.inArray(indexNumber,olArr2)!=-1)&&($.inArray(index2Number,clustered)==-1)){clustered.push(index2Number);}}}}
isClustered=($.inArray(indexNumber,clustered)!=-1);}
pushpinClass="m-pushpin "+propertyData.brand+" "+propertyData.marshaCode+" "+propertyData.pushpinNumber;if($(".my-stays-map").length>0){pushpinClass="m-pushpin "+propertyData.brand+" "+propertyData.marshaCode+" "+propertyData.pushpinNumber+" is-active-stay in-active-stay";if(propertyData.lat==pushPinLatestLatitude&&propertyData.longitude==pushPinLatestLongitude){pushpinClass="m-pushpin "+propertyData.brand+" "+propertyData.marshaCode+" "+propertyData.pushpinNumber+" is-active-stay last-stay";}
if((olArr.length>0&&olArr[0]!="")){var activemar=new Array();for(var a=0;a<olArr.length;a++){var value=olArr[a];activemar.push(propertySearchBingMap.propertiesDataArray[value].marshaCode);if($(".in-active-pin").hasClass(activemar)){pushpinClass="m-pushpin "+propertyData.brand+" "+propertyData.marshaCode+" "+propertyData.pushpinNumber+" is-active-stay";}}}
var inActiveFlag=$(".in-active-pin").hasClass(propertyData.marshaCode);if(inActiveFlag){$(".last-stay").addClass("in-active-stay");pushpinClass="m-pushpin "+propertyData.brand+" "+propertyData.marshaCode+" "+propertyData.pushpinNumber+" is-active-stay";}}
if(!isClustered){if((olArr.length>0&&olArr[0]!="")){if($(".my-stays-map").length>0){if(pushPinShowClusterValue=='true'||pushPinShowClusterValue==true){clustered.push(indexNumber);}}
pushpinClass="js-map-clustered "+pushpinClass;script="propertySearchBingMap.veZoomToGroup("+index+")";if($(".my-stays-map").length>0){propertyData.lat=propertyData.lat.trim();propertyData.longitude=propertyData.longitude.trim();}
flyoutStr="<div id='cpflyout["+propertyData.lat+"]["+propertyData.longitude+"]'  class='"+propertySearchBingMap.FLYOUT_CLASS+" m-overlay-panel is-hidden'>";flyoutStr+="<span class='t-selected-arrow'></span><i class='icon-drawer-open icon'></i> <a href='#' onmousedown='"+script+";' class='t-no-decor'>Zoom in</a>";flyoutStr+="</div>";desc=flyoutStr;$('body').append(desc);if($(".my-stays-map").length>0){if(pushPinShowTextClusterValue!=undefined||pushPinShowTextClusterValue=="true"){pushpinNumber=(olArr.length+1).toString();}}}else{if($(".my-stays-map").length>0){pushpinNumber='';}else{flyoutId=propertySearchBingMap.getFlyoutId(propertyData.lat,propertyData.longitude);desc=document.getElementById(flyoutId).innerHTML;}}
title="";icon=propertySearchBingMap.getCustomIcon("hotel");if(propertyData.type=="searchedAddress"||propertyData.type=="altLocation")
{icon=propertySearchBingMap.getCustomIcon("searchedAddress");pushpinClass='address'}
if($(".my-stays-map").length>0){pushpinOptions={text:pushpinNumber,icon:'',typeName:pushpinClass}}else{pushpinOptions={icon:icon,typeName:pushpinClass}}
loc=new propertySearchBingMap.MM.Location(Number(propertyData.lat),Number(propertyData.longitude));pushpin=new propertySearchBingMap.MM.Pushpin(loc,pushpinOptions);var dataLayer=new propertySearchBingMap.MM.EntityCollection();propertySearchBingMap.map.entities.push(dataLayer);propertySearchBingMap.MM.Events.addHandler(pushpin,'mouseover',function(e){propertySearchBingMap.displayInfobox(e);});if($(".my-stays-map").length>0){propertySearchBingMap.MM.Events.addHandler(pushpin,'click',function(e){propertySearchBingMap.displayInfobox(e);});}
propertySearchBingMap.MM.Events.addHandler(pushpin,'click',function(e){propertySearchBingMap.triggerPushpinClick(e)});propertySearchBingMap.MM.Events.addHandler(propertySearchBingMap.map,'viewchangeend',propertySearchBingMap.hideInfobox);propertySearchBingMap.MM.Events.addHandler(propertySearchBingMap.map,"mousemove",function(e){var mapElem=propertySearchBingMap.map.getRootElement();if(e.targetType!="map"){mapElem.style.cursor="pointer";}});dataLayer.push(pushpin);}}},veZoomToGroup:function(iH){var minLat,minLong,maxLat,maxLong;minLat=999;minLong=999;maxLat=-999;maxLong=-999;var olArr1,olArr2
if(propertySearchBingMap.propertiesDataArray[iH].overlapList!=""){olArr1=propertySearchBingMap.propertiesDataArray[iH].overlapList.split(",");olArr1.push(iH);for(x in olArr1){if(propertySearchBingMap.propertiesDataArray[olArr1[x]]){if(parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].lat,10)<minLat){minLat=parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].lat,10);}
if(parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].longitude,10)<minLong){minLong=parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].longitude,10);}
if(parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].lat,10)>maxLat){maxLat=parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].lat,10);}
if(parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].longitude,10)>maxLong){maxLong=parseFloat(propertySearchBingMap.propertiesDataArray[olArr1[x]].longitude,10);}}}}else{minLat=parseFloat(propertySearchBingMap.propertiesDataArray[iH].lat,10);maxLat=parseFloat(propertySearchBingMap.propertiesDataArray[iH].lat,10);minLong=parseFloat(propertySearchBingMap.propertiesDataArray[iH].longitude,10);maxLong=parseFloat(propertySearchBingMap.propertiesDataArray[iH].longitude,10);}
var ulLat=new propertySearchBingMap.MM.Location(minLat,minLong);var lrLat=new propertySearchBingMap.MM.Location(maxLat,maxLong);var llArr=new Array(ulLat,lrLat);propertySearchBingMap.map.setView({bounds:propertySearchBingMap.MM.LocationRect.fromLocations(llArr),padding:70});},setMapView:function(){if(propertySearchBingMap.locs.length==1){propertySearchBingMap.map.setView({center:new propertySearchBingMap.MM.Location(propertySearchBingMap.locs[0][0],propertySearchBingMap.locs[0][1]),zoom:15});}else if(propertySearchBingMap.locs.length==0){propertySearchBingMap.map.setView({zoom:2});}
else{propertySearchBingMap.map.setView({bounds:propertySearchBingMap.MM.LocationRect.fromLocations(propertySearchBingMap.locations),padding:70});}
propertySearchBingMap.veDoHotelClustering();propertySearchBingMap.MM.Events.addHandler(propertySearchBingMap.map,'viewchangeend',propertySearchBingMap.veDoHotelClustering);},pushpinMouseoverHandler:function(){if(!($(".my-stays-map").length>0)){$(".flyout-info-container .siteTracking").unbind();$(".flyout-info-container .siteTracking").click(function(){omnitureCustom.setupTrackingValue(this,'Yes');});}
$('a.sendto-link').unbind();$('a.sendto-link').makeSendtoLink();$(".map-flyout a.close-window").click(function(){$(".map-flyout").parent("div").hide();return false;});$(".flyout-info-container a.mi-popover").unbind();$(".flyout-info-container a.mi-popover").click(function(e){e.preventDefault();var url=$(this).attr('href');if(url!=''){popoverLightBox(url);propertySearchBingMap.hideInfobox();}});return true;},toggleMap:function(view){var mHeight=100,argSize=arguments.length;if(view=="listView"||view=="galleryView"){mHeight=0;}
else if(view=="mapView"){mHeight=100;}
if(argSize==0||(argSize>0&&$('#map').is(':empty'))){if($(".my-stays-map").length>0){propertySearchBingMap.generatePushpinData();propertySearchBingMap.getMap(propertySearchBingMap);}else{ModuleState.saveModuleState("map-toggle",this.value,function(data){propertySearchBingMap.generatePushpinData();propertySearchBingMap.getMap(propertySearchBingMap);});}}
$('#search-map-container').animate({height:mHeight+'%'},"slow");}}
propertySearchBingMap.addLoadEvent(propertySearchBingMap.init);