
$(function(){endecaSearch.init();responsiveComponents.init();unSuccessfullSell.init();recentSearch.addRecent();$('.m-search-tabs').tabs();$("#resorts-records-per-page").change(function(){$(this.form).submit();});if($('[data-searchtype=MeetingNearAddress]').length>0)$('#meeting-nearaddress-tab-link').trigger('click');$('#meeting-city-tab-link, #meeting-nearaddress-tab-link').bind('click',function(){$('#meetingevent-city-airport :input:text, #meetingevent-near-address :input:text').val('');});});$(".m-view-rate-btn a").mouseover(function(){$(this).parents().siblings('.l-best-rate').removeClass('is-hidden');});$(".m-view-rate-btn a").mouseout(function(){$(this).parents().siblings('.l-best-rate').addClass('is-hidden');});var endecaSearch={fetchedQuickViews:Array,init:function(){endecaSearch.closeMenus();lis=document.getElementsByTagName('LI');for(var i=0;i<lis.length;i++){if(lis[i].className.match("more-link")){var moreLink=utils.findChildNode(lis[i]);moreLink.onclick=endecaSearch.openMenu;}}
var advanceSearchTabs;if($('#search-forms #tabs').length>0){advanceSearchTabs=$('#search-forms').tabs();$('input:radio[name="searchType"]:checked').parents('li').find('a').click();$('input:radio[name="searchType"]').click(function(e){$(e.target).parents('li').find('a').click();});$('#search-forms ul#search-tabs a').click(function(e){$(e.target).parents('li').find(':radio').attr('checked',true);});}
if($('form.eincentive-award-form').length>0)
{$('form.eincentive-award-form').submit(endecaSearch.validate_eIncentive);}
$('.js-refine-filter').change(endecaSearch.searchRefiner);endecaSearch.dropDownOn();endecaSearch.setDropDowns();var recordsPPage=$('#recordsPerPage');if(recordsPPage.length>0)
{recordsPPage.change(endecaSearch.searchRefiner);}
var sortHD=$('#sortHD');if(sortHD.length>0){sortHD.click(endecaSearch.sortRefiner);}
var disabledFilterLink=$('#guided-nav-horizontal li a span.disabled-link');if(disabledFilterLink.length>0){disabledFilterLink.unwrap().siblings('span').hide();}
var guideNav=$("#guided-nav");if(guideNav.length>0){$('#guided-nav h2 a, #guided-nav h3 a').click(function(e){e.preventDefault();});$("#guided-nav-items").click(function(e){endecaSearch.guidedNavFilter(e);});var navCheckBoxes=$(".guided-nav-control");navCheckBoxes.each(function(e){if($(this).hasClass("selected-refinement")){$(this).attr('checked',true);}
else{$(this).attr('checked',false);}})}
var propertyResults=$("#property-results");if(propertyResults.length>0){endecaSearch.quickViewTabs();}
var switchToRedemption=$('#switch-to-redemption');if(switchToRedemption.length>0){switchToRedemption.click(function(e){endecaSearch.switchToRedemption(e);});}
var switchToCash=$('#switch-to-cash');if(switchToCash.length>0){switchToCash.click(function(e){endecaSearch.switchToCash(e);});}
if($('div.m-search-form').length>0){$('div.m-search-form h2 a, div.m-search-form h3 a').click(function(e){e.preventDefault();});var rewardsSection=$("#hidden-rewards-container");var rewardsTrigger=$("#hidden-rewards-trigger");var useRewardsPoints=$("#useRewardsPoints");var marriottRewardsNumber=$("#marriottRewardsNumber");if((useRewardsPoints.length>0&&useRewardsPoints.is(':checked'))||(marriottRewardsNumber.length>0&&marriottRewardsNumber.val()!=""&&rewardsSection.length>0)){rewardsSection.show();rewardsTrigger.children('.toggle-link').addClass("open");}}
if(document.getElementById("compare-page-container")){effects.matchHeight('hotel-info');effects.matchHeight('org');effects.matchHeight('rate-info');effects.alignBottom('rate-info');effects.matchHeight('compare-column');}
var mapObj=$('#map');var expandMap=$('#expand-map a');if(mapObj.length>0&&expandMap.length>0){expandMap.click(function(e){e.preventDefault();endecaSearch.expandCollapseMap($(this));});}
$('div.article-content').each(function(index){var options=$(this).parent('div:first').data('options'),iconPlus='<i class="icon-plus"></i>',iconMinus='<i class="icon-minus"></i>';if(options!=undefined&&options.readMore=='true'&&$(this).length>0&&$(this).height()>'110'){if($(this).find('p').length==1)$(this).addClass('l-tall-description');$(this).addClass('is-collapsed').after('<p><a href="#" class="m-read-more-toggle l-display-block">'+iconPlus+options.more+'</a></p>');var readMore=$('.m-read-more-toggle'),cityBurb=$(this);readMore.bind('click',function(e){e.preventDefault();cityBurb.toggleClass('is-collapsed');if(cityBurb.hasClass('is-collapsed')){readMore.html(iconPlus+options.more);}
else{readMore.html(iconMinus+options.less);}
MI.search.tracking.readMore($(this));});}});$('#gallery-link, #list-link').bind('click',function(e){var currentPageView=$(this).data('options').currentPageView;var toggleView=$(this).data('options').toggleView;if(toggleView==currentPageView){e.preventDefault();}});$('#view-form #gallery-link, #view-form #list-link').bind('click',function(e){var currentPageView=$(this).data('options').currentPageView;var toggleView=$(this).data('options').toggleView;e.preventDefault();if(toggleView!=currentPageView){var linkHref=$(this).attr("href");var currentResultType=$('#current-view-type');if(linkHref.indexOf('galleryView')!=-1){currentResultType.val('galleryView');}
else if(linkHref.indexOf('listView')!=-1){currentResultType.val('listView');}
$('#view-form').submit();}});},openMenu:function(){endecaSearch.closeMenus();var listItem=utils.findParentNode(this);listItem.style.display="none";while(listItem.tagName=='LI'){listItem=utils.findPreviousNode(listItem);if(!listItem){return false;}
listItem.style.display="block";}},closeMenus:function(){uls=document.getElementsByTagName('UL');for(var i=0;i<uls.length;i++){if(uls[i].className.match("collapsable-menu")){var listItem=utils.findChildNode(uls[i]);var count=1;var menuSize=6;var listParent=utils.findParentNode(uls[i]);if(utils.findParentNode(uls[i]).id=="guided-nav"){var menuSize=3;}
while(listItem!=null){if(count>menuSize){listItem.style.display="none";}
listItem=utils.findNextNode(listItem);count++;}}}
lis=document.getElementsByTagName('LI');for(var i=0;i<lis.length;i++){if(lis[i].className.match("more-link")){lis[i].style.display="block";}}},quickViewTabs:function(){$('ul.property-record-tabs a').each(function(index){var elementId=$(this).attr("id");$(this).attr("href","#"+elementId.replace('link','tab'));});$('ul.property-record-tabs li:first-child').each(function(index){$(this).removeClass("active-tab");});$('ul.property-record-tabs li a').attr("tabindex",-1);var tabs=$('.property-record-view').tabs();$(tabs).find('.ui-tabs-selected a').attr("tabindex",0);$(tabs).bind('tabsselect',function(event,ui){if(ui.index!=0){var elementId=$(ui.tab).attr("id");var start=elementId.lastIndexOf("-");var marshaCode=elementId.substring(start+1);var showLoader=elementId.match("amenities")==null;endecaSearch.loadTabContent(marshaCode,showLoader);$(this).focus();}});$("ul.property-record-tabs li a").bind('click',function(event){var parentId=$(event.target).parents('div').attr('id');var start=parentId.lastIndexOf("-");var marshaCode=parentId.substring(start+1);if($(event.target).is("a"))
{var listaobj=$(event.target);if($(listaobj).attr("tabindex")!=0){$(listaobj).parent().siblings().find('a').attr("tabindex",-1);$(listaobj).attr("tabindex",0);}
$(listaobj).focus();event.stopPropagation();event.preventDefault();}});$("ul.property-record-tabs").bind('keypress',function(event){if($(event.target).is("a"))
{var liaobj=$(event.target);event.preventDefault();if(event.which==32||event.which==13){$(liaobj).click();}}});$('div.overview-photo-panel').hover(function(){$(this).css({'z-index':'2000'});$(this).find('img.magnifying-glass').addClass('hover');var h=$(this).parents().prev(".vcard").height();var mTop=(-77+(38-h))+"px";$(this).find('img.hotel-thumb').addClass('hover').stop().animate({marginTop:mTop,width:'183px',height:'190px'},200);},function(){$(this).css({'z-index':'0'});$(this).find('img.magnifying-glass').removeClass('hover');$(this).find('img.hotel-thumb').removeClass('hover').stop().animate({marginTop:'0',width:'84px',height:'87px'},200);});$('a.hotel-thumb-link').click(function(e){e.preventDefault();sendto('no_country','no_brand',this.href,'23');});},loadTabContent:function(quickViewMarsha,showLoader){var quickViewToShow=$("#property-record-info-"+quickViewMarsha);var siteLocale=$("#site-locale").val();var loadingText=$("#loading-text").val();var logId=$("#property-record-view-"+quickViewMarsha+"-live-region");var loadedText=logId.html();if(!endecaSearch.fetchedQuickViews[quickViewMarsha]){var vData="vData=expandQuickView="+quickViewMarsha+"; path=/";document.cookie=vData;if(showLoader){quickViewToShow.find(".amenities-list").hide();quickViewToShow.addClass("loading");}
endecaSearch.fetchedQuickViews[quickViewMarsha]=true;logId.html(loadingText);HotelQuickViewRemoteService.retrievePropertyDetail(quickViewMarsha,siteLocale,function(data){if(data=={}){endecaSearch.fetchedQuickViews[quickViewMarsha]=false;return true;}
if(data.propertyHighlightsInfoVO.businessMeetingsHighlightsList!=null&&typeof data.propertyHighlightsInfoVO.businessMeetingsHighlightsList[0]!='undefined'){$("#"+quickViewMarsha+"-business-meetings").html(data.propertyHighlightsInfoVO.businessMeetingsHighlightsList[0].highlightDescription);}else{$("#"+quickViewMarsha+"-business-meetings").css("display","none");}
if(data.propertyHighlightsInfoVO.socialEventsHighlightsList!=null&&typeof data.propertyHighlightsInfoVO.socialEventsHighlightsList[0]!='undefined'){$("#"+quickViewMarsha+"-social-events-weddings").html(data.propertyHighlightsInfoVO.socialEventsHighlightsList[0].highlightDescription);}else{$("#"+quickViewMarsha+"-social-events-weddings").css("display","none");}
$("#"+quickViewMarsha+"-is-driving-direc-support").html(data.drivingDirectionsSupportedCountry);if(data.airportVOlist.length>0){$("#"+quickViewMarsha+"-airport-name").html(data.airportVOlist[0].airportFullName);$("#"+quickViewMarsha+"-airport-code").html(data.airportVOlist[0].airportCode);$("#"+quickViewMarsha+"-airport-directions").html(data.airportVOlist[0].hotelDrivingDirections);$("#"+quickViewMarsha+"-airport-alternate").html(data.airportVOlist[0].airAlternateTransport);$("#"+quickViewMarsha+"-airport-bus").html(data.airportVOlist[0].busServiceDescription);$("#"+quickViewMarsha+"-airport-subway").html(data.airportVOlist[0].subwayServiceDescription);$("#"+quickViewMarsha+"-airport-taxi").html(data.airportVOlist[0].taxiServiceDescription);}else{$(".airport-name").css("display","none");}
if(!(data.airportVOlist.length>1)){$("#"+quickViewMarsha+"-more-airports").css("display","none");}
var parkingInfo="";if(data.parkingVO.onsiteParkingDesc!=null){parkingInfo=parkingInfo+data.parkingVO.onsiteParkingDesc;}
if(data.parkingVO.valetParkingDesc!=null){if(parkingInfo!=""){parkingInfo=parkingInfo+"; ";}
parkingInfo=parkingInfo+data.parkingVO.valetParkingDesc;}
if(data.parkingVO.offsiteParkingDesc!=null){if(parkingInfo!=""){parkingInfo=parkingInfo+"; ";}
parkingInfo=parkingInfo+data.parkingVO.offsiteParkingDesc;}
if(data.parkingVO.additionalParkingInfo!=null){if(parkingInfo!=""){parkingInfo=parkingInfo+"; ";}
parkingInfo=parkingInfo+data.parkingVO.additionalParkingInfo;}
if(parkingInfo==""){$("#"+quickViewMarsha+"-parking-container").css("display","none");}
else{$("#"+quickViewMarsha+"-parking-info").html(parkingInfo);}
var drivingDirectionLink=$("#"+quickViewMarsha+"-driving-directions-link")
if(drivingDirectionLink.length>0&&!data.drivingDirectionsSupportedCountry){document.getElementById(quickViewMarsha+"-driving-directions-link").style.display="none";}
var businessMeetings=$("#"+quickViewMarsha+"-business-meetings");if(businessMeetings.length>0){businessMeetings.html(businessMeetings.text());}
var socialEventsWeddings=$("#"+quickViewMarsha+"-social-events-weddings");if(socialEventsWeddings.length>0){socialEventsWeddings.html(socialEventsWeddings.text());}
if(showLoader){quickViewToShow.removeClass("loading");quickViewToShow.find(".amenities-list").show();}
logId.html(loadedText);var vData="vData=; path=/";document.cookie=vData;});}
return false;},setDropDowns:function(){var dropDowns=$(".is-drop-down");var dropDownsAmount=dropDowns.length;dropDowns.each(function(iter,value){$(this).css("z-index",(dropDownsAmount-iter));});dropDowns.children(".t-drop-down-definition").each(function(){var dropDown=$(this);var dropDownHeight=(dropDown.siblings(".t-drop-down-title:first").outerHeight())+"px";dropDown.hide();dropDown.addClass("l-drop-down-definition");dropDown.removeClass("is-hidden");});},shutDropDowns:function(){var dropDowns=$(".is-drop-down");dropDowns.children(".t-drop-down-title").removeClass("t-drop-down-opened").find(".icon:first").removeClass("icon-triangle-up").addClass("icon-triangle-down");dropDowns.children(".t-drop-down-definition").slideUp();},dropDownOn:function(){$(".is-drop-down > .t-drop-down-title").on("click.dropDown",function(){var dropDownTitle=$(this);var dropDownDefinition=dropDownTitle.siblings(".t-drop-down-definition");var dropDown=dropDownTitle.parent();if(dropDownDefinition.length>0){if(dropDownTitle.hasClass("t-drop-down-opened")){dropDownDefinition.slideUp();dropDownTitle.removeClass("t-drop-down-opened");dropDownTitle.find(".icon:first").removeClass("icon-triangle-up").addClass("icon-triangle-down");}else{endecaSearch.shutDropDowns();dropDownDefinition.slideDown();dropDownTitle.addClass("t-drop-down-opened");dropDownTitle.find(".icon:first").removeClass("icon-triangle-down").addClass("icon-triangle-up");}}});},searchRefiner:function(){var attribute=this.name;if(attribute){var attributesValue=$(this).val();}else{var attributesValue=$(this).data('options').val;}
if(attributesValue!=""||(attribute=='currency'&&attributesValue=="")){var requestedURLObj=$(':hidden[name=requestedURL]');var requestedURL="";if(requestedURLObj.length>0){requestedURL=requestedURLObj.val().substring(requestedURLObj.val());}
if(($(':hidden[name=search-type]').val()=='HotelDirectoryResults'||$(':hidden[name=search-type]').val()=='MiniStores')&&requestedURL=="")
{window.location="/search/refineSearch.mi?"+attribute+"="+attributesValue;}
else if($(':hidden[name=search-type]').val()=='HotelDirectoryResults'||$(':hidden[name=search-type]').val()=='MiniStores'&&$(':hidden[name=miniStoreFormSubmit2]').val()=='false'){var newURL='';var requestedURL=requestedURLObj.val().substring(requestedURLObj.val());var endOfTheURL=requestedURLObj.val().substring(requestedURLObj.val().length-1);if(endOfTheURL!='/'){requestedURL=requestedURL+'/';}
var URL=requestedURL.substring(0,requestedURL.length-1);var vars=URL.split(".");for(var i=0;i<vars.length;i++){var thisOne=vars[i];if(thisOne.indexOf("page")==-1&&thisOne!='16'&&thisOne!='32'&&thisOne!='48'){newURL=newURL+thisOne+'.';}}
window.location=newURL+attributesValue+'/';}
else{window.location="/search/refineSearch.mi?"+attribute+"="+attributesValue;}}
return false;},sortRefiner:function(){var attribute=this.name;var attributesValue=$(this).val();if(attributesValue!=""){var newURL='';var requestedURL=$(':hidden[name=requestedURL]').val().substring($(':hidden[name=requestedURL]').val());var endOfTheURL=$(':hidden[name=requestedURL]').val().substring($(':hidden[name=requestedURL]').val().length-1);if(endOfTheURL!='/'){requestedURL=requestedURL+'/';}
var URL=requestedURL.substring(0,requestedURL.length-1);var vars=URL.split(".");for(var i=0;i<vars.length;i++){var thisOne=vars[i];if(thisOne.indexOf("sortBrand")==-1&&thisOne.indexOf("sortDistance")==-1&&thisOne.indexOf("sortCity")==-1&&thisOne.indexOf("sortPrice")==-1&&thisOne.indexOf("page")==-1){newURL=newURL+thisOne+'.';}}
window.location=newURL+'sort'+attributesValue+'/';}},guidedNavFilter:function(e){var guidedNavTarget=$(e.target);if(guidedNavTarget.hasClass("guided-nav-control")){var guidedNavLinkId="nav-link-"+$(guidedNavTarget).attr("id").substring(10,$(guidedNavTarget).attr("id").length);var guidedNavLink=document.getElementById(guidedNavLinkId);if($('#guided-nav').hasClass('.hotel-directory-nav')){if(typeof swa!=="undefined"){swa.linkTrackEvents='';swa.linkTrackVars='eVar14';swa.eVar14="Dimension="+$(guidedNavLink).text();if($(':hidden[name=hotelDirectoryPageType]').val()=="MiniStores")
{swa.eVar14="Ministores:Dimension="+$(guidedNavLink).text();}
void(swa.tl(this,'o','Ministores SEO page'));}}
window.location=guidedNavLink.href;}
else if($(guidedNavTarget).prop("tagName")=="A"&&$(guidedNavTarget).parent().prop("tagName")!="H3"){var guidedNavCheckboxId="nav-check-"+$(guidedNavTarget).attr("id").substring(9,$(guidedNavTarget).attr("id").length);if(document.getElementById(guidedNavCheckboxId)){var guidedNavCheckbox=document.getElementById(guidedNavCheckboxId);guidedNavCheckbox.checked=true;}
return true;}},getDate:function(daySelectBox,monthAndYearSelectBox,extraDays){var date=null;if(daySelectBox.selectedIndex!=0&&monthAndYearSelectBox.selectedIndex!=0)
{var dateArray=monthAndYearSelectBox.value.split("/");var day=Math.min(daySelectBox.value,endecaSearch.daysInMonth(dateArray[0]-1,dateArray[1]));date=new Date(dateArray[1],dateArray[0]-1,day+extraDays);}
return date;},setDate:function(daySelectBox,monthAndYearSelectBox,dateField,date){var x=0;while(x<daySelectBox.length){if(daySelectBox.options[x].value==date.getDate()){daySelectBox.selectedIndex=x;x=daySelectBox.length;}
else{x++;}}
x=0;var monthYear=(date.getMonth()+1)+"/"+date.getFullYear();while(x<monthAndYearSelectBox.length){if(monthAndYearSelectBox.options[x].value==monthYear){monthAndYearSelectBox.selectedIndex=x;x=monthAndYearSelectBox.length;}
else{x++;}}
dateField.value=(date.getMonth()+1)+"/"+date.getDate()+"/"+date.getFullYear();},daysInMonth:function(month,year){return 32-new Date(year,month,32).getDate();},buildMarriottBrandsVSParam:function(form){var checkboxGroup=form.elements["marriottBrands"];var checkboxGroupSize=checkboxGroup.length;var allCheckboxIndex=checkboxGroup.length-1;var allCheckbox=checkboxGroup[allCheckboxIndex];var vsParam=new String();if(allCheckbox.checked)
{vsParam+="All";}
else
{var numberOfSelected=0;for(counter=0;counter<checkboxGroupSize;counter++)
{if(checkboxGroup[counter].checked)
{numberOfSelected++;if(numberOfSelected>1)
{vsParam+="_";}
vsParam+=checkboxGroup[counter].value;}}}
return vsParam;},validate_eIncentive:function(){var objForm=this;var URI="/search/submitSearch.mi?"
var queryStringParams;var incentiveType_Number=$(objForm).find(":input[name=displayableIncentiveType_Number]").val();if((incentiveType_Number!='')&&(($(objForm).find(":input[name=fromDate]").val()==null||$(objForm).find(":input[name=fromDate]").val()=='')||($(objForm).find(":input[name=toDate]").val()==null||$(objForm).find(":input[name=toDate]").val()==''))){alert('Please enter check-in and check-out dates when searching by award number or type');return false;}
var city=$(objForm).find(":input[name=destinationAddress.city]").val();var state=$(objForm).find(":input[name=destinationAddress.stateProvince]").val();var country=$(objForm).find(":input[name=destinationAddress.country]").val();var fromDate=$(objForm).find(":input[name=fromDate]").val();var toDate=$(objForm).find(":input[name=toDate]").val();var roomCount=$(objForm).find(":input[name=roomCount]").val();var numGuests=$(objForm).find(":input[name=guestCount]").val();var brand=$(objForm).find(":input[name=marriottBrands]").val();var marriottRewardsNumber=$(objForm).find(":input[name=marriottRewardsNumber]").val();queryStringParams="searchType=InCity&incentiveType_Number="+incentiveType_Number+"&destinationAddress.city="+city+"&destinationAddress.stateProvince="+state+"&destinationAddress.country="+country+"&fromDate="
+fromDate+"&toDate="+toDate+"&roomCount="+roomCount+"&guestCount="+numGuests+"&marriottRewardsNumber="
+marriottRewardsNumber+"&marriottBrands="+brand;URI=URI+queryStringParams;window.open(URI,"_self");return(false);},switchToCash:function(e){e.preventDefault();var formObj=$('#edit-search-form');$(formObj).find('#useRewardsPoints').attr('checked',false).end().submit();},switchToRedemption:function(e){e.preventDefault();var formObj=$('#edit-search-form');$(formObj).find(':input[name=corporateCode]').val("").end().find(':input[name=displayableIncentiveType_Number]').val('').end().find('#none').attr('checked','true').end().find('#useRewardsPoints').attr('checked',true).end().submit();},expandCollapseMap:function(controller){var mapObj=$('#map');controller.toggleClass("up");mapObj.toggleClass("collapsed");if(controller.hasClass("up")){controller.html("<span>"+$('#reduceMap').val()+"</span>");}
else{controller.html("<span>"+$('#expandMap').val()+"</span>");}}}
if($('#unsuccessful-sell-popover').length>0){$('#page-container').attr('aria-hidden','true');}
$(window).load(function(){$('#merch-property-results .button-secondary em:contains("Afficher le calendrier")').css('font-size','105%').parent('a.button-secondary').css({'width':'150px','padding':'3px auto'});$('#merch-property-results .button-secondary em:contains("Kalender anzeigen")').css('font-size','105%').parent('a.button-secondary').css({'width':'150px','padding':'3px auto'});$('#recently-viewed .button-secondary em:contains("Afficher le calendrier")').css('font-size','105%').parent('a.button-secondary').css('width','140px');$('#recently-viewed .button-secondary em:contains("Kalender anzeigen")').css('font-size','105%').parent('a.button-secondary').css({'width':'140px','padding':'3px auto'});if($('#tool-tip').length>0){bookToolTip=$('#tool-tip');bookToolTip.fadeIn(1100).delay(6000).fadeOut(400);function bookRightFadeIn(){bookToolTip.stop().fadeIn(500);};function bookRightFadeOut(){$('.book-right-holder img').each(function(){$(this).prop("hoverIntent_s",0);});if($(bookToolTip).is(':visible')){bookToolTip.stop().fadeOut();}};var hoverBookRight={over:bookRightFadeIn,timeout:3500,out:bookRightFadeOut}
$('.book-right-holder img').each(function(){$(this).hoverIntent(hoverBookRight);});$('#room-rate-container ul.ui-tabs-nav li a').on('click',function(){bookRightFadeOut();});$('#tool-tip .close-btn').click(function(){bookRightFadeOut();return false;});brToolTipOffsetTop=$('#book-right-holder-image').offset().top
$('#tool-tip').css('top',brToolTipOffsetTop-522+'px');};if($('#unsuccessful-sell-popover').length>0){setTimeout(function(){$('#popover-panel #header').css('z-index','auto');$('#modal-util-close').focus();},50);$('#modal-util-close').click(function(){restoreAria();});$('#popover-panel').keyup(function(e){if(e.keyCode==27){restoreAria();}});function restoreAria(){$('#page-container').attr('aria-hidden','false');$('#page-container').attr('aria-live','true');};}});var mapFlyout=$(".map-flyout");mapFlyout.each(function(){var mapFlyoutSaveMe=$(this).find(".save-hotel-btn-search:first a:first");mapFlyoutSaveMe.click(function(e){e.preventDefault();var thisParent=$(this).parent();var o=thisParent.data('info');SaveHotelRemoteService.saveProperty(o.marsha,o.locale,{callback:function(data){switch(data[0]){case"exceedmax":alert(data[2]);break;case"saved":case"notsaved":thisParent.html(data[1]);break;}},timeout:5000,errorHandler:function(message){}});});});$(".price-container, .hotel-title a.fn, .map-flyout .hotel-title-link, .map-flyout .room-rate, .map-flyout .flyout-submit-button").click(function(){var dataMarsha=$(this).data('rcmarsha');if(dataMarsha!=''&&typeof(dataMarsha)!='undefined')
{$.ajax({url:'/reservation/updateSearchHistoryCookie.mi',cache:false,data:'marshaCode='+dataMarsha});}});var fnSearchToggle={init:function(oSpecialRatesContainer){$("a.toggle-link").each(function(e){if($(this).hasClass('open'))
$(this).parent().next('.toggle-container:first').show();else
$(this).parent().next('.toggle-container:first').hide();}).click(function(e){fnSearchToggle.toggleDrawerClick(e,this);});},toggleDrawerClick:function(e,obj,forceOpenClose){if($(obj).length>0){if(!forceOpenClose){if($(obj).hasClass('open'))forceOpenClose='close';}
if(e)e.preventDefault();var toggleContainer=$(obj).parent().next(".toggle-container:first"),hiddenText=$(obj).find('.is-hidden-text[data-o]');if(forceOpenClose=='close'){$(obj).removeClass('open');toggleContainer.attr('aria-expanded',false);toggleContainer.slideUp("fast");hiddenText.html(hiddenText.data('c'));}
else{$(obj).addClass('open');toggleContainer.attr('aria-expanded',true);toggleContainer.slideDown("fast",function(){$(this).css("overflow","visible");});hiddenText.html(hiddenText.data('o'));}}
return false;}}
var responsiveComponents={init:function(){$('.lt-ie9 .l-cross-linked-group:nth-child(5)').addClass('l-clear');if(typeof Response!='undefined'&&$('body').data('responsive')==true){Response.ready(function(){Response.create({prop:"width",prefix:"r",breakpoints:[0,320,480,560,672],lazy:false});checkBreakpoint();Response.crossover(function(){checkBreakpoint();},"width");function checkBreakpoint(){if(Response.band(0,320)){$('#merch-property-results').removeClass('is-viewport-medium');}
if(Response.band(321,480)){$('#merch-property-results').addClass('is-viewport-medium');}
if(Response.band(481)){$('#merch-property-results').removeClass('is-viewport-medium');}
if($('.js-drawer-xs-and-above-poi').length>0){if(Response.band(0,672)){$('.js-drawer-xs-and-above-poi').drawer({breakpoints:['M-and-below'],isOpen:false});}
if(Response.band(673)){$('.js-drawer-xs-and-above-poi').drawer({breakpoints:['MML-and-above'],isOpen:true});}}}
if($('.js-drawer-xs-and-above').length>0){$('.js-drawer-xs-and-above').drawer({breakpoints:['XS-and-above'],isOpen:searchToggles.specialRatesIsChecked(this),drawerHeaderClass:'t-drawer-handle-s',drawerContentClass:'t-drawer-content-s'});}
if($('.js-drawer-ml-and-below-brand').length>0){$('.js-drawer-ml-and-below-brand').drawer({breakpoints:['ML-and-below'],drawerHeaderClass:'t-drawer-handle-s',drawerContentClass:'t-drawer-content-s'});}
if($('.js-drawer-ml-and-below-rates').length>0){$('.js-drawer-ml-and-below-rates').drawer({breakpoints:['ML-and-below'],isOpen:searchToggles.specialRatesIsChecked('.js-drawer-ml-and-below-rates',true),drawerHeaderClass:'t-drawer-handle-s',drawerContentClass:'t-drawer-content-s'});}
$('.js-cross-link-drawer,.js-drawer-sm-and-below').drawer({breakpoints:['SM-and-below'],beforeActivate:function(e,widget){widget.$el.find('.js-menu-mainlink').click(function(e){e.preventDefault();});widget.$el.find('.js-menu-mainlink-indrawer').removeClass('is-hidden');},afterDeactivate:function(e,widget){widget.$el.find('.js-menu-mainlink').unbind('click');widget.$el.find('.js-menu-mainlink-indrawer').addClass('is-hidden');}});});}else{$('.js-hotel-title-link').each(function(){var newLink=$(this).closest('.merch-property-records').find('.js-view-rate-btn-link').attr('href');$(this).attr('href',newLink);});}}}
$(document).ready(function(){var currView=$('#merch-property-results');var poiView=$('.m-cross-poi-container');if(currView.hasClass('gallery')||currView.hasClass('map')){poiView.addClass('hidden-in-gallery');}
else{poiView.removeClass('hidden-in-gallery');}
$('.m-cross-poi-container .js-icon-drawer').click(function(e){$('.m-cross-poi-container ul').toggleClass('poi-cntr','');if($('.js-icon-drawer').hasClass('icon-plus')||$('.js-icon-drawer').hasClass('icon-minus')){$('.js-poi-less').toggleClass('is-hidden','');$('.js-poi-more').toggleClass('is-hidden','');}
if($('.js-icon-drawer').hasClass('icon-drawer-close')){$('.js-icon-drawer').addClass('icon-drawer-open');$('.js-icon-drawer').removeClass('icon-drawer-close');}
else if($('.js-icon-drawer').hasClass('icon-drawer-open')){$('.js-icon-drawer').removeClass('icon-drawer-open');$('.js-icon-drawer').addClass('icon-drawer-close');}});$('.js-toggle-view').click(function(e){var viewSelection=$(this).data('view'),container=$('#merch-property-results');var poiCurrView=$('.m-cross-poi-container');switch(viewSelection){case'map':SearchResultsViewTypeRemoteService.setViewType('mapView');poiCurrView.removeClass('hidden-in-gallery');break;case'list':SearchResultsViewTypeRemoteService.setViewType('listView');poiCurrView.removeClass('hidden-in-gallery');break;case'gallery':SearchResultsViewTypeRemoteService.setViewType('galleryView');poiCurrView.addClass('hidden-in-gallery');break;default:container.removeClass('gallery');container.removeClass('map');container.addClass('list');}});});var unSuccessfullSell={$popover:$("#popover-panel"),closeText:msgResources.closeText||'Close',loadingText:msgResources.loadingText||'Loading...',init:function(){if(this.$popover.length){$.magnificPopup.open({mainClass:'m-modal t-modal-small',items:{src:unSuccessfullSell.$popover,type:'inline'},closeMarkup:'<div class="m-modal-utilities"><button class="m-modal-close mfp-close is-hover-fix" type="button">%title% <i class="icon-close"></i></button></div>',tClose:unSuccessfullSell.closeText,tLoading:unSuccessfullSell.loadingText,callbacks:{beforeOpen:function(){this.container.attr('aria-live','assertive');},open:function(){$('#unsuccessful-nearby').on('click',function(){$.magnificPopup.close();});}}});}}}
$(function(){var editSearchForm=$('#edit-search-form:not([x-aries])');if(editSearchForm.length){new Aries.Components.SearchForm({el:editSearchForm,features:{dates:null}});}
var savedSearchForm=new Aries.Components.SearchForm({el:$('#advanced-saved-hotel-search-form'),features:{dates:null}});});