;var analytics={windowURL:(window.location.hostname+window.location.pathname),separator:(($("#analytics-separator").length>0)?$("#analytics-separator").val():"^"),analyticCookie:"mAnalytics",utilities:{getDynamicURI:function(elementObject){var dynamicElement=elementObject,elementData=dynamicElement.data("analytics"),dynamicURI;if(typeof elementData!=="undefined"&&typeof elementData.uri!=="undefined"){dynamicURI=elementData.uri;}
else if($("body#hws").length>0){dynamicURI="HWS";}
else{dynamicURI=analytics.windowURL;}
return dynamicURI;},getDynamicDescription:function(elementObject){var dynamicElement=elementObject,elementData=dynamicElement.data("analytics"),dynamicTag=dynamicElement.prop("tagName"),dynamicDescription;if(typeof elementData!=="undefined"&&typeof elementData.description!=="undefined"){dynamicDescription=elementData.description;}
if(typeof dynamicDescription==="undefined"||dynamicDescription==""){switch(dynamicTag){case"A":dynamicDescription=dynamicElement.prop("title");if(typeof dynamicDescription==="undefined"||dynamicDescription==""){dynamicElement=dynamicElement.find("img[alt]:first");if(dynamicElement.length>0){dynamicDescription=dynamicElement.prop("alt");if(typeof dynamicDescription==="undefined"||dynamicDescription==""){dynamicDescription=dynamicElement.text();}}else{dynamicElement=elementObject;dynamicDescription=dynamicElement.text();}}
break;case"BUTTON":if(dynamicElement.prop("title").length>0){dynamicDescription=dynamicElement.prop("title");}
else{dynamicDescription=dynamicElement.text();}
break;case"IMG":dynamicDescription=dynamicElement.prop("alt");break;default:dynamicElement=dynamicElement.find("a[title]:first");if(dynamicElement.length>0){dynamicDescription=dynamicElement.prop("title");}else{dynamicElement=elementObject.find("img[alt]:first");if(dynamicElement.length>0){dynamicDescription=dynamicElement.prop("alt");if(typeof dynamicDescription==="undefined"||dynamicDescription==""){dynamicDescription=dynamicElement.text();}}else{dynamicElement=elementObject;dynamicDescription=dynamicElement.text();}}};if(typeof dynamicDescription==="undefined"||dynamicDescription==""){dynamicDescription=dynamicElement.prop("id");}}
if(typeof dynamicDescription==="undefined"){dynamicDescription="";}
dynamicDescription=dynamicDescription.replace(/^\s+|\s+$/g,"").replace(/(\r\n|\n|\r)/gm,"").replace(/(\r\t|\t|\r)/gm,"");return dynamicDescription;},getDynamicLocation:function(elementObject){var dynamicLocation="",dynamicElement=elementObject,dynamicParent=elementObject.parents(".article-container:first"),elementData=dynamicElement.data("analytics");if(typeof elementData!=="undefined"){dynamicLocation=elementData.location;}
if(typeof dynamicLocation==="undefined"||dynamicLocation==""){if(dynamicParent.length>0){var dynamicParentId=dynamicParent.attr("id");if(typeof dynamicParentId!=="undefined"&&dynamicParentId.length>0){dynamicLocation=dynamicParentId;}
else{dynamicParentId="";var dynamicPageSection=dynamicParent.parents(".page-section:first");if(typeof dynamicPageSection!=="undefined"&&dynamicPageSection.length>0){dynamicParentId=dynamicPageSection.attr("id");if(typeof dynamicParentId!=="undefined"&&dynamicParentId.length>0){dynamicLocation=dynamicParentId;}
else{dynamicParentId="";}}
if(dynamicParentId==""){var dynamicParentDiv=dynamicParent.find("div[id]:first");if(dynamicParentDiv.length>0){dynamicParentId=dynamicParentDiv.attr("id");if(typeof dynamicParentId!=="undefined"&&dynamicParentId.length>0){dynamicLocation=dynamicParentId;}}}}}else{var dynamicParent=elementObject.parents(".m-search, #search-module-wrapper");if(dynamicParent.length>0){dynamicLocation="findAndReserve";}
else{var dynamicParent=elementObject.parents("#header"),dynamicParentContainer=elementObject.parents("#header-container");if(dynamicParent.length>0||dynamicParentContainer.length>0){dynamicLocation="header";}
else{var dynamicParent=elementObject.parents("#footer"),dynamicParentContainer=elementObject.parents("#footer-container");if(dynamicParent.length>0||dynamicParentContainer.length>0){dynamicLocation="footer";}}}}}
if(dynamicLocation==""||typeof dynamicLocation==="undefined"){dynamicLocation="body";}
return dynamicLocation;},getRequestType:function(action){var type="o";if(typeof action!=="undefined"){if(action.match(/.+\.pdf/i)!=null){type="d";}}
return type;},setMarshaCodeProduct:function(){if($("body#hws").length>0&&swa.products!=undefined&&swa.products.length==6){return true;}else{return false;}},getReportSuite:function(){var analyticConfiguration=$("#analytic-configuration"),analyticEnvironment=analyticConfiguration.data("environment").toLowerCase(),analyticSiteId=analyticConfiguration.data("siteid").toLowerCase(),analyticDestination="";if(analyticEnvironment=="prod"){analyticEnvironment="";}
analyticDestination="marriottGlobal"+analyticEnvironment;if(analyticSiteId!=""){if(analyticSiteId=="laca"){analyticSiteId="la";}
analyticDestination+=",marriott"+analyticSiteId+analyticEnvironment;}
return analyticDestination;},sendAnalytics:function(){var s_code=swa.t();if(s_code){$("body").append(s_code);}},sendOtherData:function(dataToSend){if(typeof swa!=="undefined"&&dataToSend.length>0){swa.events="";swa.linkTrackVars="";swa.linkTrackEvents="";var dataArray=dataToSend.split(this.separator);$.each(dataArray,function(index,value){value=value.replace(/^\s+|\s+$/g,"");var varNum=value.substring(0,value.indexOf("="));var varValue=value.substring(value.indexOf("=")+1);if(varNum==="pageName"){varValue=window.location.hostname+varValue;}
swa[varNum]=varValue;if(swa.linkTrackVars!=""){swa.linkTrackVars+=",";}
swa.linkTrackVars+=varNum;});swa.linkTrackEvents=swa.events;if(swa.linkTrackVars!=""){void(swa.tl(true,"o","Analytic Event"));}}},getCookie:function(name){var docCookie=document.cookie;if(docCookie.length>0){var beginCookie=docCookie.indexOf(name+"=");if(beginCookie!=-1){beginCookie+=name.length+1;var endCookie=docCookie.indexOf(";",beginCookie);if(endCookie==-1){endCookie=docCookie.length;}
return unescape(docCookie.substring(beginCookie,endCookie));}}
return"";},clearCookie:function(name){document.cookie=name+"=;path=/";},elementClickAnalytics:function(elem){elem.on("click.sendAnalytics",function(e){if(!$(this).hasClass("analytics-clicked")){analytics.dynamicAnalytics($(this),e);if(!$(this).hasClass('analytics-click-multi')){$(this).addClass('analytics-clicked');}}});},dynamicDataAttribute:function(){var elements=$(".js-data-analytics");if(elements.length>0){elements.each(function(index){var thisId=$(this).attr("id"),thisData=$(this).val();if((typeof thisId!=="undefined"&&thisId!="")&&(thisData!="")){var elementIdIndex=thisId.indexOf("-data-analytics");if(elementIdIndex!=-1){var elementForData=thisId.substring(0,elementIdIndex);if(elementForData!=""){thisData=$.parseJSON(thisData);$("#"+elementForData).data("analytics",thisData);}}}});}}},dynamicAnalytics:function(theElement,e){if(typeof theElement!=="undefined"&&theElement!=null){var elementData=theElement.data("analytics"),shoppingMethodDestination="/reservation/rateListMenu",dataPreventStandard,dataCustomAnalytics,dataShoppingMethod,dataSendNow;if(typeof elementData!=="undefined"){dataPreventStandard=elementData.preventStandard,dataCustomAnalytics=elementData.customData,dataShoppingMethod=elementData.shoppingMethod,dataSendNow=elementData.sendNow;}
var requestPreventStandard=(dataPreventStandard=="true"||dataPreventStandard==true);var attrRel=theElement.attr("rel"),attrTarget=theElement.attr("target"),propHref=theElement.prop("href"),propAction=theElement.prop("action");var isRelExternal=(attrRel=="external"),isNewWindow=((typeof attrTarget!=="undefined")&&attrTarget!="_self"&&attrTarget!="_parent"&&attrTarget!="_top"),isPopOver=theElement.hasClass("mi-popover"),isNotLinked=(propHref=="#");var isHover=(e.type=="mouseover");var sendNow=((dataSendNow!="false"&&dataSendNow!=false)&&((dataSendNow=="true"||dataSendNow==true)||isRelExternal||isNewWindow||isPopOver||isNotLinked||isHover));var setShoppingMethod=((dataShoppingMethod=="true"||dataShoppingMethod==true)||(typeof propHref!=="undefined"&&propHref.indexOf(shoppingMethodDestination)!=-1)||(typeof propAction!=="undefined"&&propAction.indexOf(shoppingMethodDestination)!=-1));if(sendNow){var dataDelay,dataType,requestNoDelay,requestType;if(typeof elementData!=="undefined"){dataDelay=elementData.delay,dataType=elementData.type;}
if(dataDelay=="true"||dataDelay==true){requestNoDelay=theElement;}
else{requestNoDelay=true;}
if(typeof dataType!=="undefined"){requestType=dataType;}
else{if(typeof propHref!=="undefined"){requestType=analytics.utilities.getRequestType(propHref);}else if(typeof propAction!=="undefined"){requestType=analytics.utilities.getRequestType(propAction);}else{requestType="o";}}
swa.linkTrackVars="";swa.linkTrackEvents="";swa.events="";if(analytics.utilities.setMarshaCodeProduct()){if(swa.linkTrackVars!=""){swa.linkTrackVars+=",";}
swa.linkTrackVars+="products";}
if(typeof dataCustomAnalytics!=="undefined"&&dataCustomAnalytics.length>1){var dataArray=dataCustomAnalytics.split(analytics.separator);$.each(dataArray,function(index,value){value=value.replace(/^\s+|\s+$/g,"");var varNum=value.substring(0,value.indexOf("="));var varValue=value.substring(value.indexOf("=")+1);if(varNum==="pageName"){varValue=window.location.hostname+varValue;}
swa[varNum]=varValue;if(swa.linkTrackVars!=""){swa.linkTrackVars+=",";}
swa.linkTrackVars+=varNum;});swa.linkTrackEvents=swa.events;}
if(!requestPreventStandard||setShoppingMethod){var dynamicURL=analytics.utilities.getDynamicURI(theElement),dynamicLocation=analytics.utilities.getDynamicLocation(theElement),dynamicDescription=analytics.utilities.getDynamicDescription(theElement)
if(isHover&&dynamicDescription!=""){dynamicDescription+=" Hover"}
var dynamicValue="uri="+dynamicURL+":loc="+dynamicLocation+":linkDescription="+dynamicDescription;if(!requestPreventStandard){swa.eVar1=dynamicValue;if(swa.linkTrackVars!=""){swa.linkTrackVars+=",";}
swa.linkTrackVars+="eVar1";if(swa.events!=""){swa.events+=",";}
if(isHover){swa.events+="event42";}
else{swa.events+="event2";}}
if(setShoppingMethod){swa.eVar46=dynamicValue;if(swa.linkTrackVars!=""){swa.linkTrackVars+=",";}
swa.linkTrackVars+="eVar46";if(swa.events!=""){swa.events+=",";}
swa.events+="event88";}
if(swa.linkTrackVars.indexOf("events")==-1){swa.linkTrackVars+=",events";}
swa.linkTrackEvents=swa.events;}
if(swa.linkTrackVars!=""){void(swa.tl(requestNoDelay,requestType,"Analytic Dynamic Event"));}}else{var cookieData="";if(analytics.utilities.setMarshaCodeProduct()){cookieData+=analytics.separator;cookieData+="products="+swa.products;}
if(typeof dataCustomAnalytics!=="undefined"&&dataCustomAnalytics.length>1){cookieData+=analytics.separator;cookieData+=dataCustomAnalytics;}
if(!requestPreventStandard||setShoppingMethod){var dynamicURL=analytics.utilities.getDynamicURI(theElement),dynamicLocation=analytics.utilities.getDynamicLocation(theElement),dynamicDescription=analytics.utilities.getDynamicDescription(theElement),dynamicVars="",dynamicEvents="";if(isHover&&dynamicDescription!=""){dynamicDescription+=" Hover"}
var dynamicValue="uri="+dynamicURL+":loc="+dynamicLocation+":linkDescription="+dynamicDescription;if(!requestPreventStandard){if(dynamicVars.length>0){dynamicVars+=analytics.separator;}
dynamicVars+="eVar1="+dynamicValue;if(dynamicEvents.length>0){dynamicEvents+=",";}
if(isHover){dynamicEvents+="event42";}
else{dynamicEvents+="event2";}}
if(setShoppingMethod){if(dynamicVars.length>0){dynamicVars+=analytics.separator;}
dynamicVars+="eVar46="+dynamicValue;if(dynamicEvents.length>0){dynamicEvents+=",";}
dynamicEvents+="event88";}
if(cookieData.indexOf(";")!=-1){cookieData=cookieData.replace(/\;/g,"%3B")}
cookieData+=analytics.separator;cookieData+=dynamicVars;cookieData+=analytics.separator;cookieData+="events="+dynamicEvents;}
var analyticCookie=analytics.utilities.getCookie(analytics.analyticCookie);var analyticCookieExists=(analyticCookie!=null&&analyticCookie!=undefined&&analyticCookie!="");if(!analyticCookieExists){analyticCookie="";}
if(analyticCookie!=""){if(cookieData!=""){cookieData+=analytics.separator;}
cookieData+=analyticCookie;}
document.cookie=analytics.analyticCookie+"="+cookieData+";path=/";}}},clickAnalytics:function(){$(".analytics-click, .analytics-click-multi").on("click.sendAnalytics",function(e){if(!$(this).hasClass("analytics-clicked")){analytics.dynamicAnalytics($(this),e);if(!$(this).hasClass('analytics-click-multi')){$(this).addClass('analytics-clicked');}}});},hoverAnalytics:function(){$(".analytics-hover, .analytics-hover-multi").on("mouseover.sendAnalytics",function(e){if(!$(this).hasClass("analytics-hovered")){analytics.dynamicAnalytics($(this),e);if(!$(this).hasClass('analytics-click-multi')){$(this).addClass('analytics-hovered');}}});},nonSpecifiedClickAnalytics:function(){var analyzeNonSpecifiedLinks=$("#analyze-unspecified-links");if(analyzeNonSpecifiedLinks.length>0){var analyzeNonSpecifiedLinksValue=analyzeNonSpecifiedLinks.val();if(analyzeNonSpecifiedLinksValue=="true"){$("a:not(.analytics-click > a, .analytics-click)").addClass("analytics-click");}}},personalizationAnalytics:function(){var personalizationData=$("#analytics-personalization").val(),personalizationDataLength=personalizationData.length;if(personalizationDataLength>0&&personalizationData!="[]"){if(personalizationData.charAt(0)=="["){personalizationData=personalizationData.substring(1);personalizationDataLength=personalizationData.length;}
if(personalizationData.charAt(personalizationDataLength-1)=="]"){personalizationData=personalizationData.substring(0,personalizationDataLength-1);}
personalizationData=personalizationData.split(",");$.each(personalizationData,function(index,value){var placementIndex=value.indexOf("personalizedPlacement");if(placementIndex>-1){var personalizedPlacement=value.substring(placementIndex),dataDelimatorIndex=personalizedPlacement.indexOf("|"),personalizedData=personalizedPlacement.substring(dataDelimatorIndex+1);personalizedPlacement=personalizedPlacement.substring(0,dataDelimatorIndex);var personalizedElement=$("#"+personalizedPlacement);if(personalizedElement.length>0){var dynamicLocation=analytics.utilities.getDynamicLocation(personalizedElement),dynamicDescription=analytics.utilities.getDynamicDescription(personalizedElement),dynamicURL=analytics.utilities.getDynamicURI(personalizedElement),clickLinkData="uri="+dynamicURL+":loc="+dynamicLocation+":linkDescription="+dynamicDescription;personalizedElement.attr("data-analytics",'{"customData":"eVar48='+personalizedData+analytics.separator+'eVar1='+clickLinkData+analytics.separator+'events=event2","preventStandard":"true"}');personalizedElement.addClass("analytics-click");}}else{return false;}});}},pageAnalytics:function(){var pageData=$("#analytics-page");if(pageData.length>0){var pageDataArray=pageData.val().split(this.separator);$.each(pageDataArray,function(index,value){value=value.replace(/^\s+|\s+$/g,"");var varNum=value.substring(0,value.indexOf("="));var varValue=value.substring(value.indexOf("=")+1);if(varNum==="pageName"){varValue=window.location.hostname+varValue;}
swa[varNum]=varValue;});}
pageData=$("#analytics-cms");if(pageData.length>0){var pageDataArray=pageData.val().split(this.separator);$.each(pageDataArray,function(index,value){value=value.replace(/^\s+|\s+$/g,"");var varNum=value.substring(0,value.indexOf("="));var varValue=value.substring(value.indexOf("=")+1);if(varNum==="pageName"){varValue=window.location.hostname+varValue;}
swa[varNum]=varValue;});}},orientationAnalytics:function(){var viewportWidth=$(window).width(),viewportHeight=$(window).height(),viewportDiff=viewportWidth-viewportHeight,viewportOrientation="Square",viewportBreakPoint="1024";if(typeof MI!=="undefined"&&typeof MI.breakpoints!=="undefined"&&typeof MI.breakpoints.getBreakpoint==="function"){var currentVp=MI.breakpoints.getBreakpoint("screen");if(currentVp!=""&&currentVp!=null){viewportBreakPoint=currentVp;}}
if(viewportDiff>0){viewportOrientation="Landscape";}
else if(viewportDiff<0){viewportOrientation="Portrait";}
swa.eVar20="Page Loaded on "+viewportBreakPoint+"w: "+viewportOrientation;},cookieAnalytics:function(){var jSessionId=analytics.utilities.getCookie("JSESSIONID"),mIVisitor=analytics.utilities.getCookie("MI_Visitor"),mVTGlobalControl=analytics.utilities.getCookie("globalCtrl"),nonMemberControlGroup=analytics.utilities.getCookie("Personalization"),analyticCookie=analytics.utilities.getCookie(this.analyticCookie),cookieData="";var analyticCookieExists=(analyticCookie!=null&&analyticCookie!=undefined&&analyticCookie!="");if(!analyticCookieExists){analyticCookie="";}
swa.prop56="";swa.eVar59="";swa.eVar47="";if(mIVisitor!=null&&mIVisitor!=undefined&&mIVisitor!=""){swa.prop56+=mIVisitor;}
if(jSessionId!=null&&jSessionId!=undefined&&jSessionId!=""){if(swa.prop56!=""){swa.prop56+="|";}
swa.prop56+=jSessionId;}
if(nonMemberControlGroup&&nonMemberControlGroup.length>0){nonMemberControlGroup=$.parseJSON(nonMemberControlGroup);if(nonMemberControlGroup&&$.isNumeric(nonMemberControlGroup.groupNumber)){swa.eVar47="g"+nonMemberControlGroup.groupNumber;}else{swa.eVar47="g"+0;}}
if(mVTGlobalControl!=null&&mVTGlobalControl!=undefined&&mVTGlobalControl!=""&&analyticCookie.indexOf("Global Control")==-1){swa.eVar59=mVTGlobalControl;cookieData+=this.separator+"other=Global Control";}
if(analyticCookie.length>0){var analyticData=analyticCookie.split(this.separator);$.each(analyticData,function(index,value){value=value.replace(/^\s+|\s+$/g,"");var varNum=value.substring(0,value.indexOf("="));var varValue=value.substring(value.indexOf("=")+1);if(varNum!="other"){if(varNum=="events"&&swa.events!==undefined&&swa.events!=""){swa[varNum]+=","+varValue;}else{swa[varNum]=varValue;}}});}
document.cookie=analytics.analyticCookie+"="+cookieData+";path=/";},doPageAnalytics:function(){if(typeof swa!=="undefined"){this.pageAnalytics();this.orientationAnalytics();this.cookieAnalytics();if(typeof mboxLoadSCPlugin!='undefined'){mboxLoadSCPlugin(s);}
analytics.utilities.sendAnalytics();}},doDynamicAnalytics:function(){if(typeof swa!=="undefined"){this.personalizationAnalytics();this.nonSpecifiedClickAnalytics();analytics.utilities.dynamicDataAttribute();this.clickAnalytics();this.hoverAnalytics();}},doAnalytics:function(){analytics.doPageAnalytics();$(document).ready(function(){analytics.doDynamicAnalytics();});},execute:function(){if(typeof swa==="undefined"){$.ajax({type:"GET",url:"/common/js/analytics/s_code.js",dataType:"script",cache:true}).done(function(){analytics.doAnalytics();});}else{analytics.doAnalytics();}}};var executeAnalytics=function(){if(analytics){setTimeout(function(){analytics.execute();},0);}}();