
var cashAndPoints=cashAndPoints||{action:'default',unavailableCount:0,recalculateCount:0,allRedemptionSelected:false,rph:0,initialize:function(rph){cashAndPoints.rph=rph;var container=$('#cash-points-container'),usePointsTrigger=this.getUsePointsTrigger(),pointsSelected=usePointsTrigger.prop('checked'),cashPointsComments=container.closest('td').find('.use-cash-points-comments');if($('#cash-points-results').length){cashAndPoints.close($('#cash-points-results'));}
function _update(){if(usePointsTrigger.prop('checked')){cashAndPoints.open(container);cashPointsComments.toggleClass('shaded',true);$('#cashAndPointsInput').val('true');}else{cashAndPoints.close($('#cash-points-results'));cashPointsComments.toggleClass('shaded',false);$('#cashAndPointsInput').val('false');}}
$('.use-points-trigger').not(usePointsTrigger).prop('checked',false);$('.use-cash-points-comments').removeClass('shaded');$('.use-points-trigger').unbind('change.cashAndPoints')
usePointsTrigger.bind('change.cashAndPoints',_update);_update();},open:function(container){var rph=cashAndPoints.rph;var urllink=$('#cash-points-container').data("options");$.ajax({url:urllink,cache:false,data:'page=reservationStage&action=render&rphIndex='+rph+'&ratePattern=',success:function(data){$('#cash-points-results').html(data).show();var recalculateTracking=$('#cash-points-results').find('.analytics-click');if(typeof analytics!='undefined'&&recalculateTracking.length>0){analytics.utilities.elementClickAnalytics(recalculateTracking);}
var pointsRewardTypeLinkHref=$('#pointsRewardTypeLinkHref').val();if(pointsRewardTypeLinkHref!=undefined&&pointsRewardTypeLinkHref.length>0){$('a[data-description="pointsavers"], a[data-description="seasonalawards"]').attr('href',pointsRewardTypeLinkHref);}
if($('#cPError').length>0){$('#cash-points-results').css('height','150px');cashAndPoints.ajaxCall.ajaxCover.setCover(container);cashAndPoints.ajaxCall.ajaxCover.result('error');}else{cashAndPoints.init(container,$('.cash-points-carousel'));}}});this.action='calculate';},close:function(container){var rph=cashAndPoints.rph;container.hide().html('');this.clearAllVals();this.titles('p',true);this.cleanTitles();this.action='default';this.showHideSetContinueWith(false,false);cashAndPoints.recalculateCount=0;$("form[name=dynamicChat] input[name=cashPointsRecalculated]").val(cashAndPoints.recalculateCount);cashAndPoints.unavailableCount=0;$("form[name=dynamicChat] input[name=cashPointsUnavailableItinerary]").val(cashAndPoints.unavailableCount);this.setRewardsRules(rph,'');},getUsePointsTrigger:function(){var rph=cashAndPoints.rph;return $('#cash-and-points-trigger-'+rph);}};cashAndPoints.container=function(){return $('#cash-points-container');};cashAndPoints.carousel=function(){return $('#cash-points-carousel');};$.extend(cashAndPoints,currentValues={currentVals:[],totalItems:0,setCurrentVals:function(){var cPL=this.container(),iCount=0,details=new Array();cPL.find('li').each(function(){var item=$(this).find('input:checked');if(item.length>0){iCount++;details.push(item.val());}});this.totalItems=iCount;this.currentVals=details;},getCurrentVals:function(){return this.currentVals},clearAllVals:function(){this.totalItems=0;this.currentVals.length=0;}});$.extend(cashAndPoints,functions={init:function(container,carousel){var rph=cashAndPoints.rph
var cO={btnN:'#cash-points-results .next-button a',btnP:'#cash-points-results .prev-button a',vis:7,vert:false};var responsiveCashandPoints={init:function(){if(typeof Response!='undefined'&&$('body').data('responsive')==true&&!$('body').hasClass('lt-ie9')){Response.ready(function(){Response.create({prop:"width",prefix:"r",breakpoints:[0,320,480,560,672,768,864,960,1080],lazy:false});checkBreakpoint();Response.crossover(function(){checkBreakpoint();},"width");function checkBreakpoint(){var cPRoomPool=$('.l-cash-and-points-row');if(cPRoomPool.length>0){if(Response.band(560,672)){cO.vis=6;}
if(Response.band(673,864)){cO.vis=4;}
if(Response.band(865,960)){cO.vis=5;}
if(Response.band(961,1080)){cO.vis=6;}}else{if(Response.band(672,864)){cO.vis=4;}
if(Response.band(865,960)){cO.vis=5;}}}});}}}
responsiveCashandPoints.init();var selectedItineraryName=$('#selected-itinerary').val(),selectedItinerary=this.selectedItineraryCheck(selectedItineraryName);container.slideDown();this.carouselFunctions.init(container,carousel);$(''+cO.btnN+','+cO.btnP+'').click(function(e){var carouselF=cashAndPoints.carouselFunctions;e.preventDefault();carouselF.direction=$(this).data("direction");carouselF.disabledButton=false;if($(this).hasClass('disabled'))
carouselF.disabledButton=true;});carousel.jCarouselLite({btnNext:cO.btnN,btnPrev:cO.btnP,visible:cO.vis,circular:false,beforeStart:function(){cashAndPoints.carouselFunctions.checkMonthYear(container,carousel)},afterEnd:function(){cashAndPoints.carouselFunctions.flattenMonthYear(container,carousel)}});var carouselActive=false;carousel.each(function(){var carouselItems=$(this).find('li');if(carouselItems.length>cO.vis){carouselActive=true;}});if(carouselActive){$(cO.btnN).removeClass('disabled');}
this.setCurrentVals();this.radioCheck(carousel);this.itinerarySelection();$('input',carousel).change(function(){cashAndPoints.radioCheck(carousel);});$('.cash-points-tabs').tabs({selected:selectedItinerary,select:function(event,ui){cashAndPoints.itinerarySelection(event,ui);}});miSetEqualHeight();$(".room-rate-results").off("click.recalculate");$(".room-rate-results, .js-room-rate-results").on("click.recalculate",".recalculate-link",function(e){e.preventDefault();cashAndPoints.recalculateCount++;$("form[name=dynamicChat] input[name=cashPointsRecalculated]").val(cashAndPoints.recalculateCount);cashAndPoints.ajaxCall.call(container);$(".room-rate-results").off("click.recalculate");});$('#ajax-reload a').click(function(e){e.preventDefault();location.reload();});var fifthNight=$('.fifth-night-free',container);if(fifthNight.length>0){fifthNight.hover(function(){cashAndPoints.modal.open('fifth-night-message',$(this).parents('.day-container'),container,false)},function(){cashAndPoints.modal.close()});fifthNight.click(function(e){cashAndPoints.modal.open('fifth-night-message',$(this).parents('.day-container'),container,true);e.preventDefault();});}
var descriptionLinks=$("#cash-points-results .description-link");if(descriptionLinks.length>0){descriptionLinks.hover(function(){var description=$(this).data("description");if(description!=undefined){cashAndPoints.modal.open(description+'-description',$(this).parents('.day-container'),container,false);}},function(){cashAndPoints.modal.close();}).on("click.description",function(e){if($(this).hasClass("popover")){e.preventDefault();var thisHref=$(this).attr("href");var windowURL=window.location.href;if(windowURL.match('ritz')||windowURL.match('mvci')||windowURL.match('bulgari')){var wdt='';var hgt='';var pageURL=thisHref.replace(/ /g,'%20');if(pageURL.match(/redeemRewardsPoints/)){wdt=920;hgt=500;}else{wdt=760;hgt=400;}
WinOpen(pageURL,'','100','100',wdt,hgt);}else{popoverLightBox(thisHref);}}else{var description=$(this).data("description");if(description!=undefined){cashAndPoints.modal.open(description+'-description',$(this).parents('.day-container'),container,true);e.preventDefault();}}});}
this.rphIndexLabels();cashAndPoints.showHideSetContinueWith(true,false);},rphIndexLabels:function(ui){var rph=cashAndPoints.rph
var t=$('.rph-row[data-rphindex="'+rph+'"]');var rateBlock=t.find('.rate-display, .js-rt-display'),labelTarget=$('.cash-points-tabs li.ui-tabs-selected').find('.label-target'),allRedeemptionCheck=false;if(rateBlock.find('.rate-price').length<=1){var addblock=rateBlock.find('.rate-price').detach(),current=addblock.clone().html(labelTarget.html()).addClass('current-title'),recalc=addblock.clone().html($('.recalculate-link').html()).addClass('recalculate-link');addblock.addClass('redemption-title');rateBlock.prepend(addblock,current,recalc);}else{var newCurrent=(typeof(ui)!='undefined')?$(ui.tab).find('.label-target').html():labelTarget.html(),currentTitle=rateBlock.children('.current-title');currentTitle.html(newCurrent).addClass("t-title-style-reset");var unavailableClass=(this.checkUnavailable(ui,labelTarget))?currentTitle.addClass('unavailable'):currentTitle.removeClass('unavailable');}
if(($('.rate-price.redemption-title').hasClass('show')||$('.rate-price.current-title').text().indexOf('+')==-1)&&$('.rate-price.current-title').text().indexOf('Unavailable')==-1){allRedeemptionCheck=true;}
this.titles('current',allRedeemptionCheck);},selectedItineraryCheck:function(select){var i=0;$('.tabs-links li p > a').each(function(index,value){if($(this).data('itinerary')==select){i=index;}});return i},checkUnavailable:function(ui,secondaryTarget){var checkPath=secondaryTarget;if(typeof(ui)!='undefined'){checkPath=$(ui.tab).next('span');}
return checkPath.hasClass('unavailable');},itinerarySelection:function(event,ui){var dataInfo='USER_DEFINED',selectItinerary=$('#selected-itinerary');if(ui!=undefined){dataInfo=$(ui.panel).data("type");}
if(ui!=undefined){selectItinerary.val(dataInfo);}
this.rphIndexLabels(ui);if(ui!=undefined){var continueWith=$(ui.panel).find(".selection-text:first").data("continue");}
if(continueWith!=undefined){cashAndPoints.showHideSetContinueWith(true,continueWith);}
this.setRewardsRules(dataInfo);},setRewardsRules:function(dataInfo){var rph=cashAndPoints.rph;var $selectedRow=$('.rph-row[data-rphindex="'+rph+'"]');var rateRulesLink=$selectedRow.find('.room-rules');var regExp=/(itineraryType)[^\x26]+/g;var searchQueryResults=rateRulesLink.attr('href').replace(regExp,"itineraryType="+dataInfo);rateRulesLink.attr('href',searchQueryResults);},allCash:function(results){var cPL=this.container(),cCount=0
tCount=this.totalItems;var cashReturn;for(key in results){if(results[key]==='c'){cCount++;}}
cashReturn=(cCount>=tCount-1)?true:false;return cashReturn;},allRedemption:function(results){var redemption;var rCount=0,tCount=this.totalItems;for(key in results){if(results[key]==='p'){rCount++;}}
redemption=(rCount==tCount)?true:false;cashAndPoints.allRedemptionSelected=redemption;return redemption;},collectRadioValues:function(cPL){var details=new Array();$('li',cPL).each(function(){var item=$(this).find('input:checked');if(item.length>0){details.push(item.val());}});return details;},radioCheck:function(c){var collection=this.collectRadioValues(c);if(collection.length>0){var cash=this.allCash(collection),redemption=this.allRedemption(collection),changeCount=this.changeCount(collection),usePointsCheckbox=this.getUsePointsTrigger();if(cash){this.disableRadio(true,c);}else{this.disableRadio(false,c);}
usePointsCheckbox.val('true');if(changeCount>0&&!redemption){this.titles('r',false);}else if(redemption){usePointsCheckbox.val('false');var selectItinerary=$('#selected-itinerary');selectItinerary.val('DEFAULT_RATE');this.titles('p',true);}else{this.titles('current',false);}}},changeCount:function(changeSet){var change=0,baseSet=this.currentVals;for(key in baseSet){if(baseSet[key]!=changeSet[key]){change++;}}
return change;},tabSelection:function(){},titles:function(type,allRedeemptionCheck){var rph=cashAndPoints.rph;var $selectedRow=$('.rph-row[data-rphindex="'+rph+'"]');var recalculateLink=$('.recalculate-link'),continueWith=$('.js-continue-with'),redemptionTitle=$('.redemption-title'),currentTitle=$('.current-title'),rewardRules=$selectedRow.find('.room-rules'),currentRate=$('.rate-price.current-title'),rateDescription=currentRate.parents('.rate-selection').siblings('.rate-description').find('p'),alertDesc=$('.rate-price.current-title').parents('.rate-selection').siblings('.rate-description').find('.alert'),currentUnavailable=currentRate.hasClass('unavailable'),hideDesc=false;switch(type){case'r':recalculateLink.addClass('show');redemptionTitle.removeClass('show');continueWith.addClass('hidden');currentTitle.removeClass('show');$selectedRow.find('.limited-availability-msg').hide();currentUnavailable=true;break;case'p':redemptionTitle.addClass('show');recalculateLink.removeClass('show');currentTitle.removeClass('show');currentUnavailable=false;this.showHideSetContinueWith(false);break;case'current':currentTitle.addClass('show');recalculateLink.removeClass('show');redemptionTitle.removeClass('show');break;}
if(!allRedeemptionCheck){hideDesc=true;}
var current=this.showHideRateInformation(currentUnavailable,rewardRules,rateDescription,hideDesc,alertDesc);},showHideRateInformation:function(u,rewards,descriptions,hideDesc,alertDesc){if(u){rewards.hide();descriptions.hide();}else{rewards.show();if(hideDesc){descriptions.show();alertDesc.hide()}else{descriptions.show();}}},showHideSetContinueWith:function(show,continueWithRate){if(show){var currentDisplayedRate=continueWithRate;if(!currentDisplayedRate){currentDisplayedRate=$("#cash-points-results .tab-contents:not(#cash-points-results .ui-tabs-hide) .selection-text:first").data("continue");}
if(currentDisplayedRate!=undefined&&currentDisplayedRate!=0){if(continueWith.length>0){var continueSpan=continueWith.children("span:first");if(continueSpan.length>0){continueSpan.html(currentDisplayedRate);}
else{continueWith.prepend('<span>'+currentDisplayedRate+'</span>');}}else{var buttonContainer=$("#preferences-container-buttons");var buttonHTML=$.trim(buttonContainer.html());var continueWithHTML='<p id="continue-with"><span>'+currentDisplayedRate+'</span>'+buttonHTML+'</p>';buttonContainer.html(continueWithHTML);}}}else{$("#continue-with span").remove();}},disableRadio:function(t,c){if(t){var item='';item=$('.day-container input:checked[value="p"]',c).attr('name');if(item.length>0){var disableItem=$('[name="'+item+'"][value="c"]');disableItem.attr('disabled',true);disableItem.parents('.day-container').on('mouseover',function(){cashAndPoints.modal.open('cash-only-message',$(this),c,false);}).on('mouseout',function(){cashAndPoints.modal.close();}).addClass('alert');c.addClass('all-cash');}}else{$(':radio:disabled',c).removeAttr('disabled');$('.day-container',c).off().removeClass('alert');c.removeClass('all-cash');}},cleanTitles:function(){$('.rate-price.current-title, .rate-price.recalculate-link').remove();$('.rate-price.redemption-title').removeClass('redemption-title');}});cashAndPoints.modal={modalBox:function(){return $('#cash-points-modal');},setMessage:function(msg,box){box.find('span').hide();box.find('span#'+msg+'').show();},open:function(msg,target,container,clickClose){var box=this.modalBox();this.setMessage(msg,box);var targetPos=target.offset();var boxTop=targetPos.top-box.outerHeight()-5,boxLeft=targetPos.left,arrow='left';var ulContainer=container.offset(),maxSize=ulContainer.left+(target.outerWidth()*4);if(targetPos.left>=maxSize){boxLeft=targetPos.left+target.outerWidth()-box.outerWidth();arrow='right';}
box.css({left:boxLeft,top:boxTop});$('#modal-bottom',box).addClass(arrow);$('body').append(box);var closeBtn=box.find('.close-window');closeBtn.hide();if(clickClose){var closeBtn=box.find('.close-window');closeBtn.show().click(function(e){cashAndPoints.modal.close();e.preventDefault();});}
box.show();},close:function(){var box=this.modalBox();box.find('.close-window').hide();box.hide();box.find('#modal-bottom').removeClass('right left');}};cashAndPoints.carouselFunctions={blockWidth:0,monthObj:function(c){return c.find('.month-name');},yearObj:function(c){return c.find('.year');},wrapperLeft:0,direction:'right',disabledButton:false,init:function(c,carousel){this.setBlockWidth(carousel);this.setWrapperLeft(carousel);},setMonth:function(carousel){var carouselFunctions=cashAndPoints.carouselFunctions;carousel.each(function(){var m=$(this).find('.month-name');carouselFunctions.raiseMonthYear(m[0],$(this));});},setYear:function(carousel){var carouselFunctions=cashAndPoints.carouselFunctions;carousel.each(function(){var y=$(this).find('.year');carouselFunctions.raiseMonthYear(y[0],$(this));});},setBlockWidth:function(c){this.blockWidth=c.find('li').outerWidth()-10;},setWrapperLeft:function(c){this.wrapperLeft=c.offset().left;},checkMonth:function(m,carousel){var block=this.blockWidth,direction=this.direction,monthLeft=false,monthRight=false,monthNext=false,monthPosStore=0,monthTarget;$('.cash-points-carousel').each(function(){var month=$(this).find('.month-name'),wrapper=$(this).offset().left,wrapperBlock=wrapper-block;month.each(function(){var monthPos=$(this).offset().left;monthPosStore=monthPos;if(monthPos==wrapperBlock)
monthLeft=true;if(monthPos==wrapper)
monthTarget=$(this);if(monthPos==wrapper+block)
monthRight=true;var monthCheck=$(this).parent('li').next('li').find('.month-name');if(monthCheck.length>0)
monthNext=true;});if((!monthLeft&&direction=='prev')||(!monthRight&&direction=='next')){cashAndPoints.carouselFunctions.raiseMonthYear(monthTarget,$(this));}});},checkYear:function(y,carousel){var block=this.blockWidth,direction=this.direction,yearLeft=false,yearRight=false;var yearTarget;$('.cash-points-carousel').each(function(){var year=$(this).find('.year'),wrapper=$(this).offset().left,wrapperBlock=wrapper-block;year.each(function(){var yearPos=$(this).offset().left;if(yearPos==wrapper-block){yearLeft=true;}
if(yearPos==wrapper){yearTarget=$(this);}
if(yearPos==wrapper+block){yearRight=true;}});if((!yearLeft&&direction=='prev')||(!yearRight&&direction=='next')){cashAndPoints.carouselFunctions.raiseMonthYear(yearTarget,$(this));}});},checkMonthYear:function(c,carousel){var y=carousel.find('.year'),m=carousel.find('.month-name'),direction=this.direction,disabledButton=this.disabledButton;if((direction=='prev'&&disabledButton)||(direction=='next'&&disabledButton)){return;}
this.checkMonth(m,carousel);this.checkYear(y,carousel);},flattenMonthYear:function(container,carousel){var target='',carouselFunctions=cashAndPoints.carouselFunctions;carousel.each(function(){var carousel=$(this);var month=$(this).find('.month-name');month.each(function(){if($(this).parent('li').length===0){target=$(this);carouselFunctions.flattenTarget($(this),carousel);}});var year=$(this).find('.year');year.each(function(){if($(this).parent('li').length===0){target=$(this);carouselFunctions.flattenTarget($(this),carousel);}});});},flattenTarget:function(target,carousel){var targetPos=target.offset().left;carousel.find('li').each(function(){var liPos=$(this).offset().left;if(liPos==targetPos){$(this).prepend(target);}});},raiseMonthYear:function(target,carousel){carousel.prepend(target);}};cashAndPoints.ajaxCall={url:function(){var container=cashAndPoints.container();var ajaxUrl=container.data("options");return ajaxUrl;},count:0,ajaxCover:{o:$.extend({window:'#ajax-cover',timer:0}),waitingMsg:function(){if($('#ajax-loading,#ajax-reload').css('display')!='inline'){$('#ajax-please-wait').show();}},setCover:function(c){var cover=$(this.o.window),cWidth=c.width(),cHeight=c.height();cover.css({display:'block',zIndex:'100'}).find('.ajax-background').css({opacity:'0.80',width:cWidth,height:cHeight});cover.find('.ajax-inner-container').css({left:cWidth/2-75}).find('#ajax-messaging span').css({display:'none'});cashAndPoints.ajaxCall.ajaxCover.timer=setTimeout("cashAndPoints.ajaxCall.ajaxCover.waitingMsg()",4500);},result:function(code){var cover=$(this.o.window);var ajxMsg=$('#ajax-messaging span');clearTimeout(cashAndPoints.ajaxCall.ajaxCover.timer);if(code==='success'){ajxMsg.css('display','none');$('#ajax-loading').fadeIn(500);cover.find('.ajax-background').animate({opacity:'1.0'},500);return true;}else{ajxMsg.css('display','none');$('#ajax-reload').fadeIn(800);return false;}},close:function(){var cover=$(this.o.window);cover.delay(1000).fadeOut(800);clearTimeout(cashAndPoints.ajaxCall.ajaxCover.timer);return true;}},consolidateValues:function(c){var rph=cashAndPoints.rph
var sendVals=cashAndPoints.collectRadioValues(c);var formattedVals='action='+cashAndPoints.action+'&rphIndex='+rph;if(sendVals.length>0){formattedVals+='&ratePattern=';var i=0;do{formattedVals+=sendVals[i];i++;}
while(i<sendVals.length)}
return formattedVals;},call:function(c){var ajaxCalls=cashAndPoints.ajaxCall;$.ajax({url:ajaxCalls.url(),beforeStart:ajaxCalls.ajaxCover.setCover(c),cache:false,data:this.consolidateValues(c),dataType:'html',error:function(x,status,error){ajaxCalls.ajaxCover.result(status);},timeout:15000,success:function(obj,status,j){var resultsCover=ajaxCalls.ajaxCover.result(status);$('#cash-points-results').html(obj);if($('#cPError').length>0){ajaxCalls.ajaxCover.result('error');}else{cashAndPoints.init(c,$('.cash-points-carousel',c));if(resultsCover){ajaxCalls.ajaxCover.close();}}
var firstTab=$("#cash-points-results ul.tabs-links:first li:first p:first a.tab-link:first");if(firstTab.length>0){var dataRate=firstTab.data("rate");if(dataRate!=undefined){if(dataRate.indexOf("Unavailable")>-1){cashAndPoints.unavailableCount++;$("form[name=dynamicChat] input[name=cashPointsUnavailableItinerary]").val(cashAndPoints.unavailableCount);}}}}});}};