
var body=$('body');var changeSize="";if(typeof Response!='undefined'&&$('body').data('responsive')===true){$(window).resize(function(e){checkPhotoWidth($(window).width());});function checkPhotoWidth(width){var currentSize=changeSize;if(width>=320&&width<=479){changeSize=213;}else if(width>=480&&width<=559){changeSize=324;}else if(width>=560&&width<=671){changeSize=380;}else if(width>=672){changeSize=423;}
if(currentSize!=changeSize){PHOTOGALLERY.resizeImage();}}}
if(typeof PhotoCarouselRemoteService!='undefined'&&typeof $.magnificPopup!='undefined'){if($('.js-photo-gallery').hasClass('js-video')){$(body).addClass('js-video-gallery');}else{$(body).removeClass('js-video-gallery');}
var PHOTOGALLERY=(function(photogallery,window,document,$,galleryService){var $photoGalleryLinks=null,$photoGalleryContainer=null,$photoCarousel=null,$photoInfoContainer=null,magnificPopupInstance=$.magnificPopup.instance;var options={galleryFilter:['JPG'],forwardPreload:3,backPreload:1}
loadImages=function($images){$images.each(function(){var $imageElement=$(this);if(!$imageElement.is('img')){$imageElement=$imageElement.find('img');}
if($imageElement.is('img')){if($imageElement.data('loaded')!==true){$imageElement.attr('src',$imageElement.data('orignal')+'?interpolation=progressive-bilinear&downsize=*:'+changeSize+'px');$imageElement.data('loaded',true);}}});},populateImageInfo=function($currentImage){$photoInfoContainer.find(".t-photo-caption").html(null);$photoInfoContainer.find(".t-photo-name").html($currentImage.data("imagename"));$photoInfoContainer.find(".t-image-count>span").first().html($currentImage.data("imagenumber"));$photoInfoContainer.find(".t-photo-caption").html($currentImage.data("description"));},buildCarouselItem=function(photoItem,defaultPhotoItem){var imageItem;switch(photoItem.fullImageFileFormat){case'SWF':imageItem=' <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="'+imgPath+photoItem.fullImageWidth+'" height="'+imgPath+photoItem.fullImageHeight+'" >'
+' <param name="movie" value="'+imgPath+photoItem.fullImageFile+'">'
+' <param name="quality" value="high" />'
+' <param name="wmode" value="transparent" />'
+' <embed wmode="transparent" src="'+imgPath+photoItem.fullImageFile+'" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="'+imgPath+photoItem.fullImageWidth+'" height="'+imgPath+photoItem.fullImageHeight+'"></embed>'
+' </object>';break;case'IPIX':imageItem='<applet archive="IpixViewer.jar" code="IpixViewer.class" codebase="'+imgPath+'/ipix/viewer/" width="'+photoItem.fullImageWidth+'" height="'+photoItem.fullImageHeight+'" name="IpixViewer" align="baseline">'
+'<param name="URL" value="'+imgPath+photoItem.fullImageFile+'">'
+'</applet>';break;case'MOV':imageItem='<embed src="'+imgPath+photoItem.fullImageFile+'" width="'+photoItem.fullImageWidth+'" height="'+photoItem.fullImageHeight+'" pluginspage="http://quicktime.apple.com" />';break;case'QTVR':case'MOV2':imageItem='<applet archive="ptviewer.jar" code="ptviewer.class" codebase="'+imgPath+'/ipix/viewer/" width="'+photoItem.fullImageWidth+'" height="'+photoItem.fullImageHeight+'">'
+'<param name="file" value="'+imgPath+photoItem.fullImageFile+'">'
+'<param name="auto" value="0.15">'+'<param name="barcolor" value="cccccc">'
+'<param name="bar_x" value="53">'+'<param name="bar_y" value="159">'
+'<param name="bar_width" value="240">'+'<param name="fov" value="100">'
+'<param name="fovmax" value="100">'+'<param name="pan" value="0">'
+'<param name="tilt" value="0">'
+'</applet>';break;default:imageItem=$('<img />',{src:imgPath+defaultPhotoItem.fullImageFile,alt:photoItem.imageAltTag}).attr("data-orignal",imgPath+photoItem.fullImageFile).prop('outerHTML');}
return imageItem;},buildCarouselItems=function(photoData){var nonImageMediaTypes=['SWF','IPIX','MOV','QTVR','MOV2'];var imgCount=1;var defaultImage=null;var photos=$.map(photoData,function(categoryPhotos,category){var filteredPhotos=$.grep(categoryPhotos,function(elem,index){return $.inArray(elem.fullImageFileFormat,options.galleryFilter)!==-1;});var $categoryLink=$('#nav-list>li a[data-section='+category+']');if(filteredPhotos.length===0){$categoryLink.parents('li').remove();}
else{$categoryLink.next('span').html('('+filteredPhotos.length+')');}
var combined=$.map(filteredPhotos,function(photo,index){if(defaultImage===null){if($.inArray(photo.fullImageFileFormat,nonImageMediaTypes)==-1){defaultImage=photo}}
return $('<li/>').attr('data-category',category).attr('data-imageId',index).attr('data-description',photo.shortMarketingCaption).attr('data-imageName',photo.imageName).attr('data-imageNumber',imgCount++).append(buildCarouselItem(photo,defaultImage)).prop('outerHTML');});return combined;});$photoInfoContainer.find(".t-image-count>span").last().html(imgCount-1);return photos.join("");},parseQueryString=function(url){var queryString=url.substring(url.indexOf('?')+1);var params={},queries,temp,i,l;queries=queryString.split("&");for(i=0,l=queries.length;i<l;i++){temp=queries[i].split('=');params[temp[0]]=temp[1];}
return params;},moveToRequestedImageInCarousel=function(data){var $query=$("[data-category="+data.pageID+"][data-imageid="+data.imageID+"]");if($photoCarousel!==null){$photoCarousel.trigger("slideTo",$query);}},handleSlideToImage=function(gotoUrl){var dataObject=parseQueryString(gotoUrl);moveToRequestedImageInCarousel(dataObject);},isLoading=function(){$('<div id="is-loading-photo-modal"></div>').appendTo('body');}
destroyLoading=function(){$('#is-loading-photo-modal').remove();}
openPhotoGallery=function(e){isLoading();var $elem=$(e.target);if($elem.is('img')||$elem.is('span')){$elem=$elem.parents('a');}
var photoURL=$elem.attr('rel')||$elem.attr('href');var locale=$elem.data('locale');var dataObject=$.extend({},parseQueryString(photoURL),{'locale':locale});var photoGalleryTemplate=null;var photoGalleryData=null;if(typeof(dataObject.roomTypeCode)!=='undefined'){photoGalleryTemplate=getPhotoGalleryTemplate(dataObject.marshaCode+"_"+dataObject.roomTypeCode,photoURL+"&isResponsive=true");photoGalleryData=getRoomSpecificPhotoGalleryData(dataObject.marshaCode+"_"+dataObject.roomTypeCode,dataObject);}else{photoGalleryTemplate=getPhotoGalleryTemplate(dataObject.marshaCode,photoURL+"&isResponsive=true");photoGalleryData=getPropertyPhotoGalleryData(dataObject.marshaCode,dataObject);}
$.when(dataObject,photoGalleryTemplate,photoGalleryData).done(function(dataObject,template,photoGalleryData){$photoGalleryContainer.html(template[0]);var $gallery=$photoGalleryContainer.find('.m-photo-gallery');$photoInfoContainer=$gallery.find('.m-photo-gallery-slider > .t-photo-description');$photoCarousel=$('<ul/>').prependTo($gallery.find('.m-photo-gallery-slider'));var photoItems=null;var videoItems=null,videoArray=[];if(typeof(dataObject.roomTypeCode)!=='undefined'){photoItems=buildCarouselItems(photoGalleryData);}else{photoItems=buildCarouselItems(photoGalleryData.photoTourImagesListMap);var i=0,j=0,videoItems=photoGalleryData.videoTourList;for(i in videoItems){for(j in videoItems[i]){if(j=='videoLinkUrl'){var videoLink=(videoItems[i][j]);videoArray.push(videoLink);}}}}
if($('.js-video-clicked').length>=1){var videoLnkURL=$(videoArray).get($('.js-video-clicked').attr('href').slice(-1));var iframeInsert=$('<iframe/>',{src:videoLnkURL+'?wmode=transparent',name:'video-frame',scrolling:'no',frameborder:0}).addClass('video-tour');$('.m-photo-gallery-slider').append(iframeInsert);}
$('#nav-list').on('click.photoGallery','a',function(e){$('.m-photo-gallery-slider iframe').remove();$('.js-video-clicked').removeClass('js-video-clicked');var $elem=$(this);if($elem.is('.photo-tour-video')){if($('.video-tour').length){$('.video-tour').remove()}
var clickedVideo=$('#nav-list a.photo-tour-video').index(this);var videoLnkURL=$(videoArray).get(clickedVideo);var iframeInsert=$('<iframe/>',{src:videoLnkURL+'?wmode=transparent',name:'video-frame',scrolling:'no',frameborder:0}).addClass('video-tour');$('.m-photo-gallery-slider').children().hide();$('.m-photo-gallery-slider').append(iframeInsert);}
else{$('.m-photo-gallery-slider').find('.video-tour').remove();$('.m-photo-gallery-slider').children().show();handleSlideToImage($elem.attr('rel')||$elem.attr('href'));}
$('#view-category-trigger').click();return false;});$photoCarousel.append(photoItems);$photoCarousel.carouFredSel({circular:false,infinite:false,responsive:true,items:{visible:1},scroll:{fx:"directscroll",onBefore:function(data){loadImages(data.items.visible);populateImageInfo(data.items.visible);if($photoDescription.length){$photoDescription.addClass("is-collapsed").next('.t-photo-caption').fadeOut('fast');}
if($('body').hasClass('ie8')||$('body').hasClass('ie7')){var currentImg=$(data.items.visible).find('img');var theImage=new Image();theImage.src=currentImg.attr("src");$(currentImg).width(theImage.width).height(theImage.height);}},onAfter:function(data){loadImages(data.items.old.prevAll().slice(0,options.backPreload));loadImages(data.items.visible.nextAll().slice(0,options.forwardPreload));photoCap=$('.t-photo-caption');}},onCreate:function(data){loadImages(data.items);populateImageInfo(data.items);loadImages(data.items.prevAll().slice(0,options.backPreload));loadImages(data.items.nextAll().slice(0,options.forwardPreload));$gallery.addClass('mfp-hide');photoCap=$('.t-photo-caption');},auto:false,prev:{button:".m-photo-gallery-slider .previous-btn",key:"left"},next:{button:".m-photo-gallery-slider .next-btn",key:"right"},swipe:true});var $categoryTrigger=$('#view-category-trigger');if($categoryTrigger.length){$categoryTrigger.click(function(e){e.preventDefault();var trigger=$(this);var target=$('#nav-list');var hotelNameDisplay=$('.m-photo-gallery-header .t-hotel-name');if($(hotelNameDisplay).is(':visible')){target.css({top:trigger.position().top+30,left:trigger.position().left-44});}else{target.css({top:trigger.position().top+30,left:trigger.position().left});}
target.slideToggle();})}
var $photoDescription=$('.t-photo-description>.t-photo-info');if($photoDescription.length){$photoDescription.addClass('is-collapsed').next('.t-photo-caption').hide();$photoDescription.on('click',function(){$(this).toggleClass("is-collapsed").next('.t-photo-caption').slideToggle();});}
$.magnificPopup.open({mainClass:"m-photo-gallery-container",showCloseBtn:false,items:{src:$gallery,type:'inline'},callbacks:{beforeOpen:function(){$('#page-container').attr('aria-hidden','true');},close:function(){$photoCarousel.trigger("destroy");$('#page-container').removeAttr('aria-hidden');$('.m-photo-gallery-slider iframe').remove();$('.js-video-clicked').removeClass('js-video-clicked');}}});magnificPopupInstance.content.resize();moveToRequestedImageInCarousel(dataObject);destroyLoading();});return false;},createCache=function(requestFunction){var cache={};return function(key,data){if(!cache[key]){cache[key]=$.Deferred(function(defer){requestFunction(defer,key,data);}).promise();}
return cache[key];};},getPhotoGalleryTemplate=createCache(function(defer,key,dataObject){$.get(dataObject).then(defer.resolve,defer.reject);});getPropertyPhotoGalleryData=createCache(function(defer,key,dataObject){galleryService.getPropertyPhotoGallery(dataObject.marshaCode,dataObject.locale,{callback:function(data){defer.resolve(data);},timeout:50000,errorHandler:function(message){defer.reject(message)}});});getRoomSpecificPhotoGalleryData=createCache(function(defer,key,dataObject){galleryService.getRoomTypeSpecificPhotoGallery(dataObject.marshaCode,dataObject.locale,dataObject.roomTypeCode,{callback:function(data){defer.resolve(data);},timeout:50000,errorHandler:function(message){defer.reject(message)}});});photogallery.resizeImage=function(){$('.m-photo-gallery-slider img').each(function(){var $imageElement=$(this);$imageElement.attr('src',$imageElement.data('orignal')+'?interpolation=progressive-bilinear&downsize=*:'+changeSize+'px');});}
photogallery.init=function(galleryLinks,settings){options=$.extend({},options,settings);$photoGalleryLinks=$(galleryLinks);$photoGalleryContainer=$('<div id="photo-gallery-lightbox"/>').css({position:'absolute',left:'-999em'});$('body').append($photoGalleryContainer);$('body').on('click.photoGallery',galleryLinks,openPhotoGallery);$('body').on('click.photoGallery','.m-photo-gallery .js-close-gallery',$.proxy(function(e){e.preventDefault();$.magnificPopup.close();$('.m-photo-gallery-slider iframe').remove();$('.js-video-clicked').removeClass('js-video-clicked');},magnificPopupInstance));}
return photogallery;}(PHOTOGALLERY||{},window,document,jQuery,PhotoCarouselRemoteService));$(function(){PHOTOGALLERY.init('.js-photo-gallery, .js-video, .js-photo-gallery>img');});}